# ============ 队名翻译补全（2026-10-01） ============
TEAM_CN_UPDATE = {
    "Deportes Tolima": "托利马体育",
    "Millonarios": "百万富翁",
    "Internacional de Bogotá": "波哥大国际",
    "Once Caldas": "卡尔达斯十一人",
    "Deportivo Pasto": "帕斯托体育",
    "América de Cali": "卡利美洲",
    "Independiente Medellín": "麦德林独立",
    "Alianza Valledupar FC": "巴耶杜帕尔联盟",
    "Cúcuta Deportivo": "库库塔体育",
    "Boyacá Chicó FC": "博亚卡奇科",
    "Rionegro Águilas Doradas": "里奥内格罗金鹰",
    "Atlético Bucaramanga": "布卡拉曼加竞技",
    "Deportes Quindío": "金迪奥体育",
    "Unión Magdalena": "马格达莱纳联盟",
    "Bogotá FC": "波哥大",
    "Tigres FC": "老虎",
    "Barranquilla FC": "巴兰基亚",
    "Real Cartagena": "皇家卡塔赫纳",
    "Envigado FC": "恩维加多",
    "Real Cundinamarca": "皇家昆迪纳马卡",
    "CSKA Sofia": "索菲亚中央陆军",
    "Levski Sofia": "索菲亚列夫斯基",
    "FC CSKA 1948 Sofia": "索菲亚中央陆军1948",
    "Lokomotiv Sofia": "索菲亚火车头",
    "Cherno More Varna": "瓦尔纳黑海",
    "Lokomotiv Plovdiv": "普罗夫迪夫火车头",
    "FK Dunav Ruse": "鲁塞多瑙河",
    "Botev Plovdiv": "普罗夫迪夫博特夫",
    "FK Spartak Varna": "瓦尔纳斯巴达克",
    "FK Septemvri Sofia": "索菲亚九月",
    "Botev Vratsa": "弗拉察博特夫",
    "Universitatea Craiova": "克拉约瓦大学",
    "FCSB": "布加勒斯特星",
    "CFR 1907 Cluj": "克卢日",
    "FCV Farul Constanța": "康斯坦察灯塔",
    "FC Dinamo București": "布加勒斯特迪纳摩",
    "FC Botoșani": "博托沙尼",
    "FC Voluntari": "沃尔伦塔里",
    "Sepsi OSK Sfântu Gheorghe": "圣格奥尔基塞普西",
    "FC Rapid București": "布加勒斯特快速",
    "FC Corvinul Hunedoara": "胡内多阿拉科维努尔",
    "FK Csíkszereda Miercurea Ciuc": "米耶尔库雷亚丘克",
    "FC Thun": "图恩",
    "Servette FC": "塞尔维特",
    "FC Lausanne-Sport": "洛桑体育",
    "FC Luzern": "卢塞恩",
    "BSC Young Boys": "伯尔尼年轻人",
    "FC Zürich": "苏黎世",
    "Basel": "巴塞尔",
    "Grasshopper Club Zürich": "苏黎世草蜢",
    "Fenerbahçe": "费内巴切",
    "North Carolina Courage": "北卡罗来纳勇气",
    "Angel City FC": "天使城",
    "Racing Louisville": "路易斯维尔竞技",
    "Denver Summit FC": "丹佛峰",
    "Seattle Reign FC": "西雅图君临",
    "Washington Spirit": "华盛顿精神",
    "Kansas City Current": "堪萨斯城潮流",
    "Utah Royals FC": "犹他皇家",
    "San Diego Wave FC": "圣迭戈波浪",
    "Boston Legacy FC": "波士顿遗产",
    "Lexington SC": "莱克星顿SC",
    "Monterey Bay FC": "蒙特雷湾",
    "Loudoun United FC": "劳登联",
    "FC Tampa Bay Rowdies": "坦帕湾暴徒",
    "CRB": "CRB",
    "Grêmio Novorizontino": "新奥里藏蒂诺",
    "Middlesbrough": "米德尔斯堡",
    "Norwich City": "诺维奇",
    "Leyton Orient": "莱顿东方",
    "Fleetwood Town": "弗利特伍德",
    "Reading": "雷丁",
    "Sheffield United": "谢菲尔德联",
    "Millwall": "米尔沃尔",
    "Peterborough United": "彼得堡联",
    "Southampton": "南安普顿",
    "York City": "约克城",
    "Wycombe Wanderers": "韦康比流浪者",
    "Grimsby Town": "格林斯比",
    "Crewe Alexandra": "克鲁",
    "Watford": "沃特福德",
    "Stoke City": "斯托克城",
    "Barnsley": "巴恩斯利",
    "Cardiff City": "卡迪夫城",
    "Preston North End": "普雷斯顿",
    "AFC Wimbledon": "AFC温布尔登",
    "Plymouth Argyle": "普利茅斯",
    "Chesterfield": "切斯特菲尔德",
    "Crawley Town": "克劳利",
    "Charlton Athletic": "查尔顿",
    "Woking": "沃金",
    "Harrogate Town": "哈罗盖特",
    "Walsall": "沃尔索尔",
    "Birmingham City": "伯明翰",
    "Lincoln City": "林肯城",
    "Boston United": "波士顿联",
    "Shrewsbury Town": "什鲁斯伯里",
    "Stevenage": "斯蒂夫尼奇",
    "Rochdale": "罗奇代尔",
    "Wrexham": "雷克瑟姆",
    "West Bromwich Albion": "西布罗姆维奇",
    "Bristol City": "布里斯托尔城",
    "Cambridge United": "剑桥联",
    "Queens Park Rangers": "女王公园巡游者",
    "Sheffield Wednesday": "谢菲尔德星期三",
    "Burton Albion": "伯顿",
    "Stockport County": "斯托克波特",
    "Gillingham": "吉林汉姆",
    "Leicester City": "莱斯特城",
    "Derby County": "德比郡",
    "Bradford City": "布拉德福德",
    "Bristol Rovers": "布里斯托尔流浪者",
    "Colchester United": "科尔切斯特联",
    "Rotherham United": "罗瑟汉姆",
    "Cheltenham Town": "切尔滕纳姆",
    "Bolton Wanderers": "博尔顿",
    "Oldham Athletic": "奥尔德姆",
    "Newport County": "纽波特郡",
    "Notts County": "诺茨郡",
    "Accrington Stanley": "阿克宁顿",
    "Blackpool": "布莱克浦",
    "Doncaster Rovers": "唐卡斯特",
    "Solihull Moors": "索利赫尔摩尔",
    "Yeovil Town": "耶奥维尔",
    "FC Halifax Town": "哈利法克斯",
    "Forest Green Rovers": "森林绿流浪者",
    "Kidderminster Harriers": "基德明斯特",
    "Wigan Athletic": "维冈竞技",
    "Exeter City": "埃克塞特城",
    "Blackburn Rovers": "布莱克本",
    "Boreham Wood": "博勒姆伍德",
    "Scunthorpe United": "斯肯索普联",
    "AFC Fylde": "AFC法尔德",
    "Hartlepool United": "哈特尔浦联",
    "Swansea City": "斯旺西城",
    "Bromley": "布罗姆利",
    "Salford City": "索尔福德城",
    "Mansfield Town": "曼斯菲尔德",
    "Northampton Town": "北安普顿",
    "Barnet": "巴尼特",
    "Huddersfield Town": "哈德斯菲尔德",
    "Sutton United": "萨顿联",
    "Luton Town": "卢顿",
    "Eastleigh": "伊斯特利",
    "Milton Keynes Dons": "米尔顿凯恩斯",
    "Port Vale": "维尔港",
    "Swindon Town": "斯温登",
    "Gateshead": "盖茨黑德",
    "Altrincham FC": "奥尔特林厄姆",
    "Aldershot Town": "奥尔德肖特",
    "Wealdstone": "韦尔德斯通",
    "Tamworth": "塔姆沃思",
    "Barrow AFC": "巴罗",
    "Carlisle United": "卡莱尔联",
    "Southend United": "绍森德联",
    "Hornchurch": "霍恩彻奇",
    "Worthing FC": "沃辛",
    "Oxford United": "牛津联",
    "Tranmere Rovers": "特兰米尔",
    "Portsmouth": "朴茨茅斯",
    "Tottenham Hotspur": "托特纳姆热刺",
    "Brighton & Hove Albion": "布莱顿",
    "Bury FC": "伯里",
    "Worcester City": "伍斯特城",
    "Boldmere St Michaels FC": "博尔德米尔圣迈克尔",
    "Warrington Rylands 1906 FC": "沃灵顿莱兰兹",
    "Hemel Hempstead": "赫默尔亨普斯特德",
    "Emley AFC": "埃姆利",
    "Wingate & Finchley": "温盖特与芬奇利",
    "Chippenham Town": "奇彭纳姆",
    "Witton Albion FC": "威顿阿尔比恩",
    "Ossett United": "奥塞特联",
    "Knowle FC": "诺尔",
    "Exmouth Town": "埃克斯茅斯",
    "Yate Town": "亚特",
    "Leamington": "利明顿",
    "South Shields": "南希尔兹",
    "Gorleston FC": "戈尔斯顿",
    "Barton Town": "巴顿",
    "Torquay United": "托基联",
    "Redditch United": "雷迪奇联",
    "FC United of Manchester": "曼彻斯特联FC",
    "Gainsborough Trinity": "盖恩斯伯勒三一",
    "Stratford Town": "斯特拉特福",
    "Bury Town FC": "伯里镇",
    "AFC Stoneham": "斯托纳姆",
    "Workington": "沃金顿",
    "Spennymoor Town": "斯彭尼穆尔",
    "Evesham United": "伊夫舍姆联",
    "Chorley FC": "乔利",
    "Three Bridges FC": "三桥",
    "Quorn FC": "科恩",
    "Flackwell Heath": "弗拉克韦尔希思",
    "Aveley FC": "阿夫利",
    "Curzon Ashton FC": "柯曾阿什顿",
    "Bath City": "巴斯城",
    "Cleethorpes Town": "克利索普斯",
    "Avro FC": "阿夫罗",
    "Garforth Town AFC": "加福斯",
    "Cambridge City": "剑桥城",
    "Faversham Town": "法弗舍姆",
    "Dulwich Hamlet": "德威哈姆雷特",
    "Bamber Bridge FC": "班伯布里奇",
    "Alfreton Town FC": "阿尔弗雷顿",
    "Buckhurst Hill": "巴克赫斯特山",
    "Fakenham Town": "法肯纳姆",
    "Hitchin Town": "希钦",
    "Needham Market FC": "尼德姆市场",
    "Havant & Waterlooville": "哈文特与沃特卢维尔",
    "Kettering Town": "凯特林",
    "Brentwood Town": "布伦特伍德",
    "AFC Whyteleafe": "怀特利夫",
    "Bishop Auckland": "奥克兰主教",
    "Redcar Athletic": "雷德卡竞技",
    "Weston Super Mare": "滨海韦斯顿",
    "Thame United": "泰姆联",
    "Walton & Hersham FC": "沃尔顿与赫舍姆",
    "Maidenhead United": "梅登黑德联",
    "Buxton FC": "巴克斯顿",
    "Bedford Town": "贝德福德",
    "Brackley Town": "布拉克利",
    "Dagenham & Redbridge": "达根汉姆与雷德布里奇",
    "Worksop Town FC": "沃克索普",
    "Farnborough": "法恩伯勒",
    "Truro City": "特鲁罗城",
    "Kingstonian": "金斯顿尼安",
    "Pontefract Collieries FC": "庞蒂弗拉克特煤矿",
    "Shepshed Dynamo": "谢普谢德迪纳摩",
    "Hanwell Town": "汉威尔",
    "Cheshunt FC": "切森特",
    "Bradford Park Avenue AFC": "布拉德福德公园大道",
    "Weymouth FC": "韦茅斯",
    "Hyde United FC": "海德联",
    "Wythenshawe FC": "威森肖",
    "Newcastle Town FC": "纽卡斯尔镇",
    "Maldon & Tiptree FC": "莫尔登与蒂普特里",
    "Welling United FC": "威灵联",
    "East Grinstead Town": "东格林斯特德",
    "Trafford FC": "特拉福德",
    "Yaxley FC": "亚克斯利",
    "Ware FC": "韦尔",
    "Biggleswade Town": "比格尔斯韦德",
    "Stanway Rovers": "斯坦韦流浪者",
    "Wellingborough Town": "韦灵伯勒",
    "Concord Rangers": "康科德流浪者",
    "Bourne Town": "伯恩",
    "Crowborough Athletic": "克劳伯勒竞技",
    "Banbury United": "班伯里联",
    "Macclesfield FC": "麦克尔斯菲尔德",
    "Wimborne Town": "温伯恩",
    "Horsham FC": "霍舍姆",
    "Ebbsfleet United": "埃布斯弗利特联",
    "Ashton United FC": "阿什顿联",
    "King's Lynn Town": "金斯林",
    "AFC Portchester": "波特切斯特",
    "Waltham Abbey": "沃尔瑟姆修道院",
    "Telford United": "特尔福德联",
    "Uxbridge": "阿克斯布里奇",
    "Merthyr Town": "梅瑟蒂德菲尔",
    "Atlético Madrid": "马德里竞技",
    "Club Atlético de Madrid": "马德里竞技",
    "Real Sociedad B": "皇家社会B",
    "Real Oviedo": "皇家奥维耶多",
    "Eibar": "埃瓦尔",
    "SD Eibar": "埃瓦尔",
    "Burgos Club de Fútbol": "布尔戈斯",
    "UD Las Palmas": "拉斯帕尔马斯",
    "Sporting Gijón": "希洪竞技",
    "Córdoba": "科尔多瓦",
    "AD Ceuta": "休达",
    "Albacete Balompié": "阿尔瓦塞特",
    "CD Eldense": "埃尔登塞",
    "CD Tenerife": "特内里费",
    "Costa Adeje Tenerife": "特内里费",
    "Granada": "格拉纳达",
    "Granada Club de Fútbol": "格拉纳达",
    "Leganés": "莱加内斯",
    "Real Valladolid": "皇家巴利亚多利德",
    "FC Andorra": "安道尔",
    "CE Sabadell": "萨瓦德尔",
    "Madrid CFF": "马德里CFF",
    "Celta Fortuna": "塞尔塔福图纳",
    "RCD Espanyol de Barcelona": "西班牙人",
    "CD Castellón": "卡斯特利翁",
    "Real Club Deportivo de A Coruña": "拉科鲁尼亚",
    "Fútbol Club Barcelona": "巴塞罗那",
    "FC Badalona": "巴达洛纳",
    "Logroño United": "洛格罗尼奥联",
    "US Boulogne Côte-d'Opale": "布洛涅",
    "Pau FC": "波城",
    "Metz": "梅斯",
    "Sochaux": "索肖",
    "Clermont Foot": "克莱蒙",
    "USL Dunkerque": "敦刻尔克",
    "Rodez AF": "罗德兹",
    "Nantes": "南特",
    "Montpellier": "蒙彼利埃",
    "Stade de Reims": "兰斯",
    "Red Star FC": "红星",
    "Dijon": "第戎",
    "Stade Lavallois": "拉瓦勒",
    "Grenoble Foot 38": "格勒诺布尔",
    "Guingamp": "甘冈",
    "Annecy FC": "阿讷西",
    "Saint-Étienne": "圣埃蒂安",
    "Nancy": "南锡",
    "AS Monaco": "摩纳哥",
    "C.F. Os Belenenses": "贝伦人",
    "Amarante FC": "阿马兰特",
    "Varzim SC": "瓦尔津",
    "Penafiel": "佩纳菲耶尔",
    "Tondela": "通德拉",
    "CD Mafra": "马夫拉",
    "Feirense": "费伦斯",
    "AVS - Futebol SAD": "AVS",
    "AD Fafe": "法菲",
    "Académica Coimbra": "科英布拉大学",
    "Atletico CP": "竞技CP",
    "União de Leiria": "莱里亚联盟",
    "Torreense": "托雷恩塞",
    "Portimonense SAD": "波尔蒂芒人",
    "Leixões SC": "莱雄伊什",
    "GD Vitória Sernache": "塞纳谢维多利亚",
    "Felgueiras": "费尔盖拉斯",
    "Chaves": "沙维什",
    "Lusitano Ginásio Clube": "卢西塔诺",
    "SC Covilhã": "科维良",
    "AD Marco 09": "马尔科09",
    "Vizela": "维泽拉",
    "CD Trofense": "特罗芬塞",
    "Lusitânia Lourosa": "洛罗萨卢西塔尼亚",
    "Paços de Ferreira": "费雷拉",
    "SC Vianense": "维亚纳",
    "SC São João Ver": "圣若昂维尔",
    "Caldas SC": "卡尔达斯",
    "USC Paredes": "帕雷德斯",
    "SC Farense": "法鲁人",
    "UD Santarém": "圣塔伦",
    "Louletano DC": "洛莱塔诺",
    "UD Oliveirense": "奥利维伦斯",
    "Leça FC": "莱萨",
    "CD Fátima": "法蒂玛",
    "Estrela Calheta FC": "卡列塔星",
    "AD Fazendense": "法曾登塞",
    "SC Beira-Mar": "贝拉马尔",
    "SU Sintrense": "辛特伦塞",
    "Real SC": "皇家SC",
    "O Elvas CAD": "埃尔瓦斯",
    "CD Cinfães": "辛方伊什",
    "AD Ponte da Barca": "蓬蒂达巴尔卡",
    "FC Serpa": "塞尔帕",
    "Mortágua": "莫尔塔瓜",
    "FC Alverca B": "阿尔韦卡B",
    "SC Mineiro Aljustrelense": "阿尔茹斯特雷尔矿工",
    "FC Vinhais": "维尼艾什",
    "At. Malveira": "马尔韦拉竞技",
    "AD Sanjoanense": "圣若昂人",
    "1º Dezembro": "12月1日",
    "Gd Nazarenos": "纳扎雷诺斯",
    "Guarda FC": "瓜尔达",
    "Associação Naval 1893": "海军1893",
    "Sport Comércio e Salgueiros": "萨尔盖罗斯",
    "FC Tirsense": "蒂尔森塞",
    "GD Alcochetense": "阿尔科谢滕塞",
    "Sertanense": "塞尔坦嫩塞",
    "União Desportiva da Serra": "塞拉联盟",
    "Grupo Desportivo de Bragança": "布拉干萨",
    "GD Lagoa": "拉戈阿",
    "SC Maria da Fonte": "玛丽亚达丰特",
    "Imortal Deportivo Clube": "不死体育",
    "AD Castro Daire": "卡斯特罗代雷",
    "AD Ovarense": "奥瓦伦塞",
    "Amora FC": "阿莫拉",
    "Oliveira Hospital": "奥利维拉医院",
    "AD Os Limianos": "利米亚诺斯",
    "AD Camacha": "卡马查",
    "FC Maia Lidador": "马亚利达多尔",
    "CF Marialvas": "马里亚尔瓦斯",
    "CD Celoricense": "塞洛里库",
    "CO Montijo": "蒙蒂茹",
    "UD Sousense": "索森塞",
    "Benfica Castelo Branco": "本菲卡布朗库堡",
    "AC Vila Meã": "维拉梅昂",
    "CDC Montalegre": "蒙塔莱格里",
    "Vitória de Setúbal": "塞图巴尔维多利亚",
    "GD Portel": "波特尔",
    "Chaves B": "沙维什B",
    "AD Machico": "马希库",
    "CF União de Lamas": "拉马斯联盟",
    "Brito SC": "布里托",
    "AD Nogueirense": "诺盖伦塞",
    "SC Braga B": "布拉加B",
    "Santa Clara Azores B": "圣克拉拉B",
    "SC Penalva do Castelo": "佩纳尔瓦杜卡斯特洛",
    "CD Paços de Brandão": "帕苏斯德布兰当",
    "Rebordosa AC": "雷博尔多萨",
    "JD Lajense": "拉延塞",
    "Vitória SC B": "吉马良斯B",
    "Arezzo": "阿雷佐",
    "Benevento": "贝内文托",
    "Mantova": "曼托瓦",
    "Union Brescia": "布雷西亚联",
    "Ravenna": "拉文纳",
    "US Avellino 1912": "阿韦利诺",
    "Padova": "帕多瓦",
    "Modena": "摩德纳",
    "Carrarese": "卡拉雷塞",
    "Juve Stabia": "斯塔比亚尤文",
    "Virtus Entella": "恩特拉",
    "Cesena": "切塞纳",
    "OFI Crete": "克里特OFI",
    "AEK Athens": "雅典AEK",
    "Olympiacos FC": "奥林匹亚科斯",
    "PS Kalamata": "卡拉马塔",
    "GFS Panetolikos": "帕内托利科斯",
    "NPS Volos": "沃洛斯",
    "Aris Thessaloniki": "塞萨洛尼基阿里斯",
    "APS Atromitos Athinon": "雅典阿特罗米托斯",
    "AE Kifisia": "基菲夏",
    "Asteras Aktor": "阿斯特拉斯",
    "POT Iraklis": "伊拉克利斯",
    "APO Levadiakos": "莱瓦迪亚科斯",
    "Bayer 04 Leverkusen": "勒沃库森",
    "Bahlinger SC": "巴林格",
    "Westfalia Rhynern": "威斯特法利亚里嫩",
    "FC Carl Zeiss Jena": "卡尔蔡司耶拿",
    "Rot-Weiss Essen": "红白埃森",
    "Fortuna Düsseldorf": "杜塞尔多夫",
    "1.FC Phönix Lübeck": "吕贝克凤凰",
    "SC Verl": "费尔",
    "VSG Altglienicke": "阿尔特格利尼克",
    "Hallescher FC": "哈雷",
    "Hamburg-Eimsbütteler Ballspiel Club 1911": "汉堡艾姆斯比特尔",
    "SK Slavia Praha": "布拉格斯拉维亚",
    "FC Viktoria Plzeň": "比尔森胜利",
    "AC Sparta Praha": "布拉格斯巴达",
    "Patro Eisden Maasmechelen": "马斯梅赫伦",
    "Jong KRC Genk U23": "亨克青年队",
    "KAS Eupen": "欧本",
    "KSC Lokeren": "洛克伦",
    "RFC Seraing": "塞兰",
    "Royal Excelsior Virton": "维尔通",
    "KVZ FC": "KVZ",
    "Club NXT U23": "布鲁日NXT",
    "Royal Francs Borains": "弗朗斯博兰",
    "FCV Dender": "登德尔",
    "KAA Gent Reserve U23": "根特预备队",
    "RSCA Futures U23": "安德莱赫特未来",
    "RFC Liège": "列日",
    "Sporting CP B U21": "葡萄牙体育B U21",
    "Riga FC": "里加",
    "FC Drita": "德里塔",
    "FC Kairat Almaty": "阿拉木图凯拉特",
    "FK Kauno Žalgiris": "考纳斯萨尔基里斯",
    "FK Crvena zvezda": "贝尔格莱德红星",
    "Pyunik Yerevan": "埃里温凤凰",
    "Zirə FK": "齐拉",
    "FCI Levadia Tallinn": "塔林利瓦迪亚",
    "KF Ballkani": "巴尔卡尼",
    "Hapoel Be'er Sheva": "贝尔谢巴夏普尔",
    "ŠK Slovan Bratislava": "布拉迪斯拉发斯拉夫人",
    "FC Ararat-Armenia": "亚美尼亚阿拉拉特",
    "Sabah FK": "萨巴赫",
    "Omonia Nicosia": "尼科西亚奥莫尼亚",
    "Lincoln Red Imps": "林肯红魔",
    "Shamrock Rovers": "沙姆洛克流浪者",
    "Qarabağ FK": "卡拉巴赫",
    "Víkingur Reykjavík": "雷克雅未克维京人",
    "Klaksvíkar Ítróttarfelag": "克拉克斯维克",
    "KF Egnatia": "埃格纳蒂亚",
    "Inter Club d'Escaldes": "埃斯卡尔德斯国际",
    "FC Dila Gori": "哥里迪拉",
    "FK Vardar Skopje": "斯科普里瓦尔达尔",
    "FC Spartak Trnava": "特尔纳瓦斯巴达克",
    "Floriana FC": "弗洛里亚纳",
    "FK Panevėžys": "帕涅韦日斯",
    "Atert Bissen": "阿特尔特比森",
    "Neftçi PFK": "巴库石油工人",
    "FK Liepaja": "利耶帕亚",
    "FC Alashkert": "阿拉什科特",
    "FC Malisheva": "马利舍瓦",
    "FK Železničar Pančevo": "潘切沃铁路工人",
    "SP Tre Fiori": "特雷菲奥里",
    "FC Iberia 1999": "伊比利亚1999",
    "FC Tobyl": "托博尔",
    "Dinamo Minsk": "明斯克迪纳摩",
    "APR FC": "APR",
    "FC Alpendorada": "阿尔彭多拉达",
    "AIK": "AIK索尔纳",
    "SJK": "SJK塞伊奈约基",
    "Paide Linnameeskond": "派德",
    "Flora Tallinn": "塔林弗洛拉",
    "Bohemian FC": "波希米亚人",
    "The New Saints": "新圣徒",
    "Larne FC": "拉恩",
    "Coleraine FC": "科尔雷恩",
    "MAS de Fès": "非斯MAS",
    "Union Sportive Amal Tiznit": "提兹尼特阿马尔",
    "Union Touarga Sport": "图瓦尔加体育",
    "Difaâ Hassani El-Jadidi": "杰迪代哈萨尼",
    "Wydad Casablanca": "卡萨布兰卡维达德",
    "Moghreb Atlético Tetuán": "得土安竞技",
    "Kawkab Athletic Club Marrakech": "马拉喀什体育",
    "Ittihad Tanger": "丹吉尔联合",
    "Fath Union Sport": "拉巴特FUS",
    "CODM Meknès": "梅克内斯",
    "Widad Temara": "特马拉维达德",
    "RS Berkane": "贝尔卡尼",
    "Renaissance Zemamra": "泽马姆拉复兴",
    "Hassania d'Agadir": "阿加迪尔哈萨尼亚",
    "MC Alger": "阿尔及尔MC",
    "JS Saoura": "萨乌拉",
    "Al-Merrikh Khartoum Club": "喀土穆梅里克",
    "Al-Hilal": "利雅得新月",
    "Al-Nassr": "利雅得胜利",
    "Abha": "艾卜哈",
    "Horoya": "霍罗亚",
    "ASEC Mimosas": "米莫萨斯",
    "Young Africans SC": "非洲年轻人",
    "Gaborone United": "哈博罗内联",
    "Power Dynamos": "电力迪纳摩",
    "Atlético Petróleos de Luanda": "罗安达石油竞技",
    "Rahimo FC": "拉希莫",
    "Stade Malien": "马里体育场",
    "Colombe FC": "科隆布",
    "ASN Nigelec": "尼日尔电力",
    "SOBEMAP FC": "索贝马普",
    "União Desportiva do Songo": "松戈联盟",
    "FC San Pedro": "圣佩德罗",
    "Swehly SC": "斯韦利",
    "ASC Kara": "卡拉",
    "Primeiro de Agosto": "八月一日",
    "Desportivo da Huíla": "威拉体育",
    "Wiliete SC": "维利埃特",
    "1º de Maio de Benguela": "本格拉五月一日",
    "FC Luanda": "罗安达",
    "Académica Petróleos do Lobito": "洛比托石油大学",
    "Recreativo do Libolo": "利博洛娱乐",
    "CD Lunda Sul": "南隆达",
    "Cienciano": "西恩西亚诺",
    "Montevideo City Torque": "蒙得维的亚城扭矩",
    "LDU": "基多大学",
    "Independiente del Valle": "山谷独立",
    "Recoleta FC": "雷科莱塔",
    "Universidad Católica": "天主教大学",
    "Cerro Porteño": "波特诺山丘",
    "Coquimbo Unido": "科金博联",
    "Macará": "马卡拉",
    "Olimpia": "奥林匹亚",
    "Nacional": "民族",
    "Universidad Central": "中央大学",
    "Club Sporting Cristal": "水晶体育",
    "Shakhtar Donetsk": "顿涅茨克矿工",
    "Peninsula Power": "半岛电力",
    "Lions FC": "狮子FC",
    "Moreton City Excelsior FC": "莫顿城",
    "Wynnum Wolves FC": "温纳姆狼",
    "Rochedale Rovers": "罗奇代尔流浪者",
    "Magic United TFA": "魔术联",
    "Brisbane Roar Youth": "布里斯班狮吼青年队",
    "Olympic FC": "奥林匹克FC",
    "Brisbane City": "布里斯班城",
    "Eastern Suburbs": "东郊",
    "Florgrade FC": "弗洛格拉德",
    "Korona II Kielce": "凯尔采科罗纳二队",
    "Wikęd Luzino": "卢齐诺",
    "KS Górnik Polkowice": "波尔科维采矿工",
    "OKS Sokół Ostróda": "奥斯特鲁达猎鹰",
    "ŁKS Łódź": "罗兹",
    "ETO FC Győr": "杰尔",
    "Debreceni VSC": "德布勒森",
}

# ============ 合并到 data.py ============
import shutil
shutil.copy('data.py', 'data.py.bak_teams')

with open('data.py', 'a', encoding='utf-8') as f:
    f.write("\n\n# ==== 2026-10-01 队名批量补全 ====\n")
    f.write("TEAM_CN.update({\n")
    for k, v in TEAM_CN_UPDATE.items():
        f.write(f'    {k!r}: {v!r},\n')
    f.write("})\n")

print(f"OK: 已追加 {len(TEAM_CN_UPDATE)} 条翻译到 data.py")
print("备份: data.py.bak_teams")