# -*- coding: utf-8 -*-
"""
data.py —— 所有固定配置。改球队名、联赛名、参数，只改这个文件。
"""

from datetime import timezone, timedelta
CST = timezone(timedelta(hours=8))

# ============ 密钥兜底 ============
_FALLBACK_SECRETS = {
    "BSD_TOKEN": "5d8f48995ad96cead191f0611fdc042ece77b77c",
    "API_FOOTBALL_KEY": "d00cc95c3d639618d9313dc86f883685",
}

# ============ 权重常量 ============
INJURY_WEIGHT_PER_PLAYER = 0.05
INJURY_WEIGHT_MIN = 0.70
H2H_WEIGHT_LOW = 0.80
H2H_WEIGHT_HIGH = 1.10

# ============ API 地址 ============
API_FOOTBALL_BASE = "https://v3.football.api-sports.io"
BSD_BASE = "https://sports.bzzoiro.com/api/v2"
ESPN_BASE = "https://site.api.espn.com/apis/site/v2/sports/soccer"

# ============ V5.0 模型参数 ============
DIXON_COLES_RHO = {"top": -0.10, "mid": -0.13, "low": -0.15, "friendly": -0.13}

MATCH_TIER_MULTIPLIER = {
    "friendly": 0.88, "nations_league": 0.95, "qualifier": 0.98,
    "tournament": 1.00, "cup": 0.96, "league": 1.00,
}

BLEND_WEIGHT_MODEL = {"top": 0.40, "mid": 0.55, "low": 0.70}

FOOTBALL_API_LEAGUE_IDS = {
    "eng.1": 39, "esp.1": 140, "ger.1": 78, "ita.1": 135, "fra.1": 61,
    "uefa.champions": 2, "uefa.europa": 3, "uefa.nations": 5,
    "ned.1": 88, "por.1": 94, "bra.1": 71, "usa.1": 253, "mex.1": 262,
    "chn.1": 169, "jpn.1": 98, "kor.1": 292, "aus.1": 188, "sau.1": 307,
    "eng.2": 40, "tur.1": 203, "bel.1": 144, "sco.1": 179,
}

MOTIVATION_WEIGHT = {
    "title_race": {"home": 1.05, "away": 1.03},
    "european": {"home": 1.03, "away": 1.015},
    "mid_table": {"home": 1.00, "away": 1.00},
    "relegation": {"home": 1.03, "away": 0.98},
}

ESPN_LEAGUES = {
    "eng.1": "英超", "esp.1": "西甲", "ger.1": "德甲", "ita.1": "意甲", "fra.1": "法甲",
    "uefa.champions": "欧冠", "uefa.europa": "欧联杯", "ned.1": "荷甲", "por.1": "葡超",
    "bra.1": "巴甲", "usa.1": "美职联", "mex.1": "墨超", "chn.1": "中超", "jpn.1": "日职联",
    "kor.1": "韩K联", "aus.1": "澳超", "sau.1": "沙特联", "eng.2": "英冠",
    "tur.1": "土超", "bel.1": "比甲", "sco.1": "苏超",
}

# ============ 联赛等级 ============
LEAGUE_GRADE = {
    "中北美国家联赛": "S", "尼日利亚超": "S", "挪超": "S", "Superliga": "S",
    "欧冠": "S", "Copa Sudamericana": "S", "Carabao Cup": "S", "Austrian Bundesliga": "S",
    "美职联": "A", "英格兰全国联赛": "A", "FA Cup": "A", "葡萄牙杯": "A",
    "美国USL": "A", "La Liga": "A", "荷甲": "A", "德甲": "A",
    "Puchar Polski": "A", "Trendyol Super Lig": "A",
    "Tunisian Ligue Professionnelle 1": "A", "CAF Champions League": "A",
    "Copa Libertadores": "A", "Emperor Cup": "A", "巴乙": "A",
    "Liga Profesional de Fútbol": "A", "Brasileirão Serie A": "A",
    "日职联": "A", "Pro League": "A", "波兰甲": "A", "英乙": "A",
    "沙特联": "A", "Girabola": "A", "欧国联": "A", "意杯": "A",
    "Copa do Brasil": "A", "Super League": "A", "欧联杯": "A",
    "英超": "F", "英冠": "F", "英甲": "F", "西乙": "F", "苏超": "F",
    "韩K联": "F", "意甲": "F", "摩洛哥甲": "F", "哥伦比亚甲": "F",
    "Liga Portugal Betclic": "F", "国际友谊": "F", "西班牙女足": "F",
    "美国女足": "F", "墨超": "F", "Liga 3": "F", "Liga Portugal 2": "F",
    "Stoiximan Super League": "F", "Danish Superliga": "F",
}

# ============ 联赛中文名 ============
LEAGUE_CN = {
    "Premier League": "英超", "LaLiga": "西甲", "Serie A": "意甲",
    "Bundesliga": "德甲", "Ligue 1": "法甲", "Champions League": "欧冠",
    "Europa League": "欧联杯", "Eredivisie": "荷甲", "Primeira Liga": "葡超",
    "Championship": "英冠", "Super Lig": "土超", "Jupiler Pro League": "比甲",
    "Super League Greece": "希腊超", "Russian Premier League": "俄超",
    "Ukrainian Premier League": "乌超", "Bundesliga Austria": "奥甲",
    "Super League Switzerland": "瑞士超", "Superliga Denmark": "丹超",
    "Allsvenskan": "瑞典超", "Eliteserien": "挪超",
    "Scottish Premiership": "苏超", "League Two": "英乙",
    "League One": "英甲", "Ekstraklasa": "波兰甲",
    "Coppa Italia": "意杯", "Copa del Rey": "国王杯",
    "Coupe de France": "法国杯", "DFB Pokal": "德国杯",
    "UEFA Nations League": "欧国联",
    "Serie A Brazil": "巴甲", "Brasileirão Serie B": "巴乙",
    "Liga Profesional Argentina": "阿甲", "MLS": "美职联",
    "Liga MX": "墨超", "NWSL": "美国女足",
    "Categoría Primera A": "哥伦比亚甲",
    "Segunda División": "西乙", "Liga F": "西班牙女足",
    "Chinese Super League": "中超", "J1 League": "日职联",
    "K League 1": "韩K联", "A-League": "澳超", "Saudi Pro League": "沙特联",
    "Nigeria Premier Football League": "尼日利亚超",
    "Botola Pro": "摩洛哥甲",
    "CONCACAF Nations League": "中北美国家联赛",
    "International": "国际赛", "Club Friendlies": "俱乐部友谊",
    "International Friendly Games": "国际友谊",
    "FIFA World Cup": "世界杯", "UEFA European Championship": "欧洲杯",
    "Copa America": "美洲杯", "Africa Cup of Nations": "非洲杯",
    "USL Championship": "美国USL", "United Soccer League": "美国USL",
    "Liga MX Apertura": "墨超",
    "Campeonato de Portugal": "葡萄牙杯", "Taça de Portugal": "葡萄牙杯",
    "National League": "英格兰全国联赛",
    "National League North": "英议北",
    "National League South": "英议南",
    "Liga Profesional de Fútbol": "阿甲",
}

# ============ 球队中文名 ============
TEAM_CN = {
    "Arsenal": "阿森纳", "Aston Villa": "阿斯顿维拉", "Bournemouth": "伯恩茅斯",
    "Brentford": "布伦特福德", "Brighton": "布莱顿", "Burnley": "伯恩利",
    "Chelsea": "切尔西", "Crystal Palace": "水晶宫", "Everton": "埃弗顿",
    "Fulham": "富勒姆", "Leeds": "利兹联", "Liverpool": "利物浦",
    "Manchester City": "曼城", "Manchester United": "曼联",
    "Newcastle": "纽卡斯尔联", "Nottingham Forest": "诺丁汉森林",
    "Sunderland": "桑德兰", "Tottenham": "托特纳姆热刺",
    "West Ham": "西汉姆联", "Wolves": "狼队", "Wolverhampton": "狼队",
    "Ipswich Town": "伊普斯维奇", "Coventry City": "考文垂", "Hull City": "赫尔城",
    "Real Madrid": "皇家马德里", "Barcelona": "巴塞罗那",
    "Atletico Madrid": "马德里竞技", "Sevilla": "塞维利亚",
    "Real Betis": "皇家贝蒂斯", "Valencia": "瓦伦西亚",
    "Villarreal": "比利亚雷亚尔", "Athletic Bilbao": "毕尔巴鄂竞技",
    "Athletic Club": "毕尔巴鄂竞技", "Real Sociedad": "皇家社会",
    "Girona": "赫罗纳", "Osasuna": "奥萨苏纳", "Elche": "埃尔切",
    "Mallorca": "马洛卡", "Almería": "阿尔梅里亚", "Cádiz": "加的斯",
    "Deportivo Alavés": "阿拉维斯", "Getafe": "赫塔菲",
    "Rayo Vallecano": "巴列卡诺", "Espanyol": "西班牙人",
    "Levante UD": "莱万特", "Celta Vigo": "塞尔塔",
    "Deportivo de A Coruña": "拉科鲁尼亚", "Real Racing Club": "桑坦德竞技",
    "Málaga CF": "马拉加", "FC Barcelona": "巴塞罗那",
    "Bayern Munich": "拜仁慕尼黑", "Borussia Dortmund": "多特蒙德",
    "RB Leipzig": "莱比锡红牛", "Bayer Leverkusen": "勒沃库森",
    "Eintracht Frankfurt": "法兰克福", "Stuttgart": "斯图加特",
    "Wolfsburg": "沃尔夫斯堡", "Union Berlin": "柏林联合", "Freiburg": "弗赖堡",
    "FC Bayern München": "拜仁慕尼黑", "VfB Stuttgart": "斯图加特",
    "1. FC Union Berlin": "柏林联合", "SC Freiburg": "弗赖堡",
    "TSG Hoffenheim": "霍芬海姆", "FC Augsburg": "奥格斯堡",
    "SV Werder Bremen": "云达不来梅", "FC Schalke 04": "沙尔克04",
    "Hamburger SV": "汉堡", "1. FC Köln": "科隆",
    "Borussia M'gladbach": "门兴格拉德巴赫", "1. FSV Mainz 05": "美因茨",
    "SC Paderborn 07": "帕德博恩", "SV 07 Elversberg": "埃尔弗斯贝格",
    "1. FC Heidenheim": "海登海姆", "Holstein Kiel": "基尔",
    "VfL Bochum 1848": "波鸿", "SpVgg Greuther Fürth": "菲尔特",
    "Eintracht Braunschweig": "布伦瑞克", "SG Dynamo Dresden": "德累斯顿迪纳摩",
    "Hertha BSC": "柏林赫塔", "1. FC Magdeburg": "马格德堡",
    "FC St. Pauli": "圣保利", "VfL Wolfsburg": "沃尔夫斯堡",
    "Darmstadt 98": "达姆施塔特", "Energie Cottbus": "科特布斯",
    "Karlsruher SC": "卡尔斯鲁厄", "1. FC Kaiserslautern": "凯泽斯劳滕",
    "1. FC Nürnberg": "纽伦堡", "Hannover 96": "汉诺威96",
    "Arminia Bielefeld": "比勒费尔德", "VfL Osnabrück": "奥斯纳布吕克",
    "Inter": "国际米兰", "AC Milan": "AC米兰", "Juventus": "尤文图斯",
    "Napoli": "那不勒斯", "Roma": "罗马", "Lazio": "拉齐奥",
    "Atalanta": "亚特兰大", "Fiorentina": "佛罗伦萨", "Bologna": "博洛尼亚",
    "Torino": "都灵", "Udinese": "乌迪内斯", "Genoa": "热那亚",
    "Parma": "帕尔马", "Cagliari": "卡利亚里", "Como": "科莫",
    "Lecce": "莱切", "Venezia": "威尼斯", "Monza": "蒙扎",
    "Sassuolo": "萨索洛", "Frosinone": "弗罗西诺内",
    "Hellas Verona": "维罗纳", "SSC Napoli": "那不勒斯",
    "AS Roma": "罗马", "L.R. Vicenza": "维琴察", "Catania": "卡塔尼亚",
    "Palermo": "巴勒莫", "Cremonese": "克雷莫纳", "Sampdoria": "桑普多利亚",
    "Pisa": "比萨", "Empoli": "恩波利", "Ascoli": "阿斯科利",
    "Potenza Calcio": "波坦察", "Catanzaro": "卡坦扎罗",
    "Südtirol": "南蒂罗尔",
    "Paris Saint-Germain": "巴黎圣日耳曼", "Marseille": "马赛",
    "Lyon": "里昂", "Monaco": "摩纳哥", "Lille": "里尔",
    "Rennes": "雷恩", "Nice": "尼斯", "Lens": "朗斯",
    "Stade Rennais": "雷恩", "Stade Brestois": "布雷斯特",
    "Toulouse": "图卢兹", "Troyes": "特鲁瓦", "Angers": "昂热",
    "Auxerre": "欧塞尔", "Le Havre": "勒阿弗尔", "Le Mans": "勒芒",
    "Lorient": "洛里昂", "Olympique Lyonnais": "里昂",
    "Olympique de Marseille": "马赛", "Paris FC": "巴黎FC",
    "RC Strasbourg": "斯特拉斯堡", "RC Lens": "朗斯",
    "Ajax": "阿贾克斯", "PSV": "埃因霍温", "PSV Eindhoven": "埃因霍温",
    "Feyenoord": "费耶诺德", "AZ Alkmaar": "阿尔克马尔",
    "FC Twente": "特温特", "FC Utrecht": "乌德勒支",
    "SC Heerenveen": "海伦芬", "FC Groningen": "格罗宁根",
    "NEC Nijmegen": "奈梅亨", "Go Ahead Eagles": "前进之鹰",
    "PEC Zwolle": "兹沃勒", "Sparta Rotterdam": "鹿特丹斯巴达",
    "Fortuna Sittard": "福图纳锡塔德", "Willem II Tilburg": "蒂尔堡威廉二世",
    "SC Cambuur": "坎布尔", "Excelsior": "埃克塞尔西奥",
    "SC Telstar": "特尔斯达", "ADO Den Haag": "海牙",
    "AFC Ajax": "阿贾克斯", "FC Emmen": "埃门",
    "Benfica": "本菲卡", "Porto": "波尔图", "Sporting CP": "葡萄牙体育",
    "FC Porto": "波尔图", "Sporting Braga": "布拉加",
    "Vitória SC": "吉马良斯", "FC Arouca": "阿罗卡",
    "Rio Ave": "里奥阿维", "Moreirense": "莫雷伦斯",
    "CS Marítimo": "马里迪莫", "Santa Clara": "圣克拉拉",
    "Estoril Praia": "埃斯托里尔", "Famalicão": "法马利康",
    "FC Alverca": "阿尔韦尔卡", "Casa Pia": "卡萨皮亚",
    "Gil Vicente": "吉尔维森特", "CD Nacional": "国民队",
    "CF Estrela Amadora": "阿马多拉之星", "Académico Viseu FC": "维塞乌",
    "Liga Portugal Betclic": "葡超",
    "SL Benfica B": "本菲卡B队", "FC Porto B": "波尔图B队",
    "Sporting CP B U21": "葡萄牙体育B队",
    "Club Brugge KV": "布鲁日", "Club Brugge": "布鲁日",
    "RSC Anderlecht": "安德莱赫特", "KRC Genk": "亨克",
    "KAA Gent": "根特", "Standard Liège": "标准列日",
    "Royal Antwerp FC": "安特卫普", "Cercle Brugge": "色格拉布鲁日",
    "KV Mechelen": "梅赫伦", "KV Kortrijk": "科特赖克",
    "KVC Westerlo": "韦斯特洛", "Oud-Heverlee Leuven": "勒芬",
    "Sint-Truidense VV": "圣图尔登", "RC Sporting Charleroi": "沙勒罗瓦",
    "SV Zulte Waregem": "祖尔特瓦雷海姆", "SK Beveren": "贝弗伦",
    "Lommel SK": "洛默尔", "RAAL La Louvière": "拉卢维耶尔",
    "Royale Union Saint-Gilloise": "圣吉罗斯",    "Celtic": "凯尔特人", "Rangers": "流浪者",
    "Aberdeen": "阿伯丁", "Heart of Midlothian": "哈茨",
    "Hibernian": "希伯尼安", "Dundee FC": "邓迪FC",
    "Dundee United": "邓迪联", "Motherwell": "马瑟韦尔",
    "St. Mirren": "圣米伦", "St. Johnstone": "圣约翰斯通",
    "Kilmarnock": "基尔马诺克", "Falkirk FC": "福尔柯克",
    "Galatasaray": "加拉塔萨雷", "Fenerbahce": "费内巴切",
    "Beşiktaş JK": "贝西克塔斯", "Trabzonspor": "特拉布宗体育",
    "Başakşehir FK": "巴萨克赛尔", "Konyaspor": "科尼亚体育",
    "Kayserispor": "开塞利体育", "Alanyaspor": "阿拉尼亚体育",
    "Gaziantep FK": "加济安泰普", "Kasımpaşa": "卡森帕萨",
    "Samsunspor": "萨姆松体育", "Göztepe": "戈兹特佩",
    "Erzurumspor FK": "埃尔祖鲁姆", "Amed Sportif Faaliyetler": "阿梅德体育",
    "Çaykur Rizespor": "里泽体育", "Eyüpspor": "埃于普体育",
    "Kocaelispor": "科贾埃利", "Gençlerbirliği": "根塞尔伯里吉",
    "Çorum FK": "乔鲁姆", "Al Faisaly": "费萨里",
    "Flamengo": "弗拉门戈", "Palmeiras": "帕尔梅拉斯",
    "Corinthians": "科林蒂安", "São Paulo": "圣保罗",
    "Santos": "桑托斯", "Fluminense": "弗鲁米嫩塞",
    "Vasco da Gama": "瓦斯科达伽马", "Botafogo": "博塔弗戈",
    "Atlético Mineiro": "米内罗竞技", "Cruzeiro": "克鲁塞罗",
    "Grêmio": "格雷米奥", "Internacional": "巴西国际",
    "Red Bull Bragantino": "红牛布拉甘蒂诺", "Athletico": "巴拉纳竞技",
    "Bahia": "巴伊亚", "Vitória": "维多利亚",
    "Coritiba": "科里蒂巴", "Chapecoense": "沙佩科恩斯",
    "Mirassol": "米拉索尔", "Remo": "雷莫",
    "Cuiabá": "库亚巴", "Criciúma": "克里西乌马",
    "Juventude": "尤文图德", "Fortaleza": "福塔莱萨",
    "Ceará": "塞阿拉", "América Mineiro": "米内罗美洲",
    "Goiás": "戈亚斯", "Náutico": "瑙蒂科",
    "São Bernardo": "圣贝尔纳多", "Botafogo-SP": "博塔弗戈SP",
    "Ponte Preta": "庞特普雷塔", "Novorizontino": "新奥里藏蒂诺",
    "Vila Nova FC": "维拉诺瓦", "CRB": "CRB",
    "Sport Recife": "累西腓体育", "Avaí": "阿瓦伊",
    "Londrina": "隆德里纳", "Operário-PR": "巴拉纳工人",
    "Atlético Goianiense": "戈亚尼亚竞技", "毕尔巴鄂竞技": "毕尔巴鄂竞技",
    "Boca Juniors": "博卡青年", "River Plate": "河床",
    "Racing Club": "竞技俱乐部", "Independiente": "独立",
    "San Lorenzo": "圣洛伦索", "Vélez Sarsfield": "萨斯菲尔德",
    "Estudiantes de La Plata": "拉普拉塔大学生",
    "Gimnasia y Esgrima": "拉普拉塔体操",
    "Huracán": "飓风", "Rosario Central": "罗萨里奥中央",
    "Newell's Old Boys": "纽维尔老男孩", "Talleres": "塔列雷斯",
    "CA Talleres": "塔列雷斯", "Instituto De Córdoba": "科尔多瓦学院",
    "Belgrano": "贝尔格拉诺", "Club Atlético Belgrano": "贝尔格拉诺",
    "Argentinos Juniors": "阿根廷青年人", "Tigre": "蒂格雷",
    "CA Lanús": "拉努斯", "Banfield": "班菲尔德",
    "Defensa y Justicia": "防卫与正义", "Aldosivi": "阿尔多西维",
    "Central Córdoba": "中央科尔多瓦", "Barracas Central": "巴拉克中央",
    "Club Atlético Platense": "普拉滕斯",
    "Club Atlético Unión de Santa Fe": "圣菲联",
    "CA Independiente": "独立", "Independiente Rivadavia": "里瓦达维亚独立",
    "Atlético Tucumán": "图库曼竞技", "Sarmiento": "萨米恩托",
    "Deportivo Riestra": "里斯特拉", "Gimnasia y Esgrima Mendoza": "门多萨体操",
    "Estudiantes de Río Cuarto": "里奥夸尔托学生",
    "Arsenal de Sarandí": "萨兰迪阿森纳", "Colón": "科隆",
    "Inter Miami": "迈阿密国际", "LA Galaxy": "洛杉矶银河",
    "LAFC": "洛杉矶FC", "Los Angeles FC": "洛杉矶FC",
    "New York Red Bulls": "纽约红牛", "New York City FC": "纽约城",
    "Atlanta United": "亚特兰大联", "Austin FC": "奥斯汀FC",
    "Charlotte FC": "夏洛特FC", "Chicago Fire": "芝加哥火焰",
    "FC Cincinnati": "辛辛那提FC", "Colorado Rapids": "科罗拉多急流",
    "Columbus Crew": "哥伦布机员", "FC Dallas": "达拉斯FC",
    "DC United": "华盛顿联", "Houston Dynamo": "休斯顿迪纳摩",
    "Minnesota United": "明尼苏达联", "CF Montréal": "蒙特利尔",
    "Nashville SC": "纳什维尔", "New England Revolution": "新英格兰革命",
    "Orlando City SC": "奥兰多城", "Philadelphia Union": "费城联",
    "Portland Timbers": "波特兰伐木者", "Real Salt Lake": "皇家盐湖城",
    "San Jose Earthquakes": "圣何塞地震", "Seattle Sounders FC": "西雅图海湾人",
    "Sporting Kansas City": "堪萨斯城竞技", "St.Louis City": "圣路易斯城",
    "Toronto FC": "多伦多FC", "Vancouver Whitecaps": "温哥华白帽",
    "San Diego FC": "圣地亚哥FC",
    "Cruz Azul": "蓝十字", "Tigres UANL": "老虎大学",
    "Club América": "墨西哥美洲", "墨西哥美洲": "墨西哥美洲",
    "CD Guadalajara": "瓜达拉哈拉", "Club León": "莱昂",
    "Club Tijuana": "蒂华纳", "Atlas FC": "阿特拉斯",
    "Pumas UNAM": "美洲狮", "CF Monterrey": "蒙特雷",
    "Club Necaxa": "内卡萨", "CF Pachuca": "帕丘卡",
    "Santos Laguna": "桑托斯拉古纳", "Club Puebla": "普埃布拉",
    "Querétaro FC": "克雷塔罗", "Atlético San Luis": "圣路易斯竞技",
    "FC Juárez": "华雷斯", "CD Toluca": "托卢卡",
    "Atlante FC": "阿特兰特", "蓝十字": "蓝十字", "老虎大学": "老虎大学",
    "Shanghai Port": "上海海港", "上海海港": "上海海港",
    "Shandong Taishan": "山东泰山", "山东泰山": "山东泰山",
    "Beijing Guoan": "北京国安", "北京国安": "北京国安",
    "Shanghai Shenhua": "上海申花", "上海申花": "上海申花",
    "Chengdu Rongcheng": "成都蓉城", "Wuhan Three Towns": "武汉三镇",
    "Zhejiang": "浙江队", "Henan FC": "河南队",
    "Tianjin Jinmen Tiger": "天津津门虎", "Yunnan Yukun": "云南玉昆",
    "Qingdao Hainiu": "青岛海牛", "Qingdao West Coast": "青岛西海岸",
    "Dalian Yingbo FC": "大连英博", "Liaoning Tieren FC": "辽宁铁人",
    "Shenzhen Peng City": "深圳新鹏城",
    "Chongqing Tonglianglong FC": "重庆铜梁龙",
    "Yokohama F. Marinos": "横滨水手", "Kashima Antlers": "鹿岛鹿角",
    "Gamba Osaka": "大阪钢巴", "Urawa Red Diamonds": "浦和红钻",
    "Cerezo Osaka": "大阪樱花", "Vissel Kobe": "神户胜利船",
    "FC Tokyo": "东京FC", "Tokyo Verdy": "东京绿茵",
    "Kawasaki Frontale": "川崎前锋", "Sanfrecce Hiroshima": "广岛三箭",
    "Nagoya Grampus": "名古屋鲸八", "Kashiwa Reysol": "柏太阳神",
    "Machida Zelvia": "町田泽维亚", "Shimizu S-Pulse": "清水心跳",
    "Kyoto Sanga FC": "京都不死鸟", "Avispa Fukuoka": "福冈黄蜂",
    "V-Varen Nagasaki": "长崎成功丸", "Fagiano Okayama": "冈山雉鸡",
    "JEF United Chiba": "千叶市原", "Mito Hollyhock": "水户蜀葵",
    "Sagan Tosu": "鸟栖砂岩", "Ventforet Kofu": "甲府风林",
    "Jubilo Iwata": "磐田喜悦", "Hokkaido Consadole Sapporo": "札幌冈萨多",
    "Tokushima Vortis": "德岛漩涡", "Kataller Toyama": "富山胜利",
    "Tegevajaro Miyazaki": "宫崎特格瓦雅罗", "FC Imabari": "今治FC",
    "Tochigi City FC": "枥木市FC", "Fujieda MYFC": "藤枝MYFC",
    "Pohang Steelers": "浦项制铁", "Jeonbuk Hyundai Motors": "全北现代",
    "Ulsan HD": "蔚山HD", "FC Seoul": "首尔FC",
    "Incheon United": "仁川联", "Gangwon FC": "江原FC",
    "Gwangju FC": "光州FC", "Jeju SK": "济州SK",
    "Daejeon Hana Citizen": "大田韩亚市民", "Bucheon FC 1995": "富川FC",
    "Gimcheon Sangmu FC": "金泉尚武", "FC Anyang": "安养FC",
    "Al Hilal": "利雅得新月", "Al Nassr": "利雅得胜利",
    "Al-Ittihad": "吉达联合", "Al-Ahli": "吉达国民",
    "Al-Shabab": "利雅得青年人", "Al-Ettifaq": "伊蒂法克",
    "Al-Taawoun": "布赖代合作", "Al-Fateh": "哈萨征服",
    "Al-Riyadh": "利雅得", "Al-Khaleej": "哈利吉",
    "Al-Hazem": "哈兹姆", "Al-Kholood": "科鲁德",
    "Al-Qadsiah": "卡迪西亚", "Al-Fayha": "费哈",
    "Neom SC": "新未来城", "Diriyah": "迪里耶",    "England": "英格兰", "France": "法国", "Germany": "德国",
    "Spain": "西班牙", "Italy": "意大利", "Portugal": "葡萄牙",
    "Netherlands": "荷兰", "Belgium": "比利时", "Croatia": "克罗地亚",
    "Brazil": "巴西", "Argentina": "阿根廷", "Japan": "日本",
    "South Korea": "韩国", "China": "中国", "USA": "美国",
    "United States": "美国", "Peru": "秘鲁", "Chile": "智利",
    "Mexico": "墨西哥", "Colombia": "哥伦比亚", "Canada": "加拿大",
    "Australia": "澳大利亚", "New Zealand": "新西兰",
    "Uruguay": "乌拉圭", "Ecuador": "厄瓜多尔", "Paraguay": "巴拉圭",
    "Bolivia": "玻利维亚", "Venezuela": "委内瑞拉",
    "Panama": "巴拿马", "Uzbekistan": "乌兹别克斯坦",
    "Kyrgyzstan": "吉尔吉斯斯坦", "Tajikistan": "塔吉克斯坦",
    "Iran": "伊朗", "Iraq": "伊拉克", "Syria": "叙利亚",
    "Palestine": "巴勒斯坦", "Jordan": "约旦", "Lebanon": "黎巴嫩",
    "Maldives": "马尔代夫", "Morocco": "摩洛哥",
    "Tunisia": "突尼斯", "Algeria": "阿尔及利亚", "Egypt": "埃及",
    "Senegal": "塞内加尔", "Nigeria": "尼日利亚", "Ghana": "加纳",
    "Cameroon": "喀麦隆", "South Africa": "南非",
    "Norway": "挪威", "Denmark": "丹麦", "Sweden": "瑞典",
    "Poland": "波兰", "Austria": "奥地利", "Switzerland": "瑞士",
    "Serbia": "塞尔维亚", "Greece": "希腊", "Türkiye": "土耳其",
    "Ukraine": "乌克兰", "Romania": "罗马尼亚", "Hungary": "匈牙利",
    "Czechia": "捷克", "Slovakia": "斯洛伐克", "Slovenia": "斯洛文尼亚",
    "Scotland": "苏格兰", "Wales": "威尔士", "Ireland": "爱尔兰",
    "Northern Ireland": "北爱尔兰", "Iceland": "冰岛",
    "Finland": "芬兰", "Estonia": "爱沙尼亚", "Latvia": "拉脱维亚",
    "Lithuania": "立陶宛", "Belarus": "白俄罗斯", "Moldova": "摩尔多瓦",
    "Georgia": "格鲁吉亚", "Armenia": "亚美尼亚", "Azerbaijan": "阿塞拜疆",
    "Kazakhstan": "哈萨克斯坦", "Bulgaria": "保加利亚",
    "Albania": "阿尔巴尼亚", "North Macedonia": "北马其顿",
    "Montenegro": "黑山", "Bosnia & Herzegovina": "波黑",
    "Kosovo": "科索沃", "Malta": "马耳他", "Luxembourg": "卢森堡",
    "Liechtenstein": "列支敦士登", "Andorra": "安道尔",
    "San Marino": "圣马力诺", "Gibraltar": "直布罗陀",
    "Faroe Islands": "法罗群岛", "Cyprus": "塞浦路斯",
    "Israel": "以色列", "Saudi Arabia": "沙特阿拉伯",
    "Qatar": "卡塔尔", "United Arab Emirates": "阿联酋",
    "India": "印度", "Thailand": "泰国",
    "Vietnam": "越南", "Indonesia": "印度尼西亚", "Malaysia": "马来西亚",
    "Singapore": "新加坡", "Philippines": "菲律宾",
    "Hong Kong": "中国香港", "Chinese Taipei": "中华台北",
    "Costa Rica": "哥斯达黎加", "Honduras": "洪都拉斯",
    "Guatemala": "危地马拉", "El Salvador": "萨尔瓦多",
    "Nicaragua": "尼加拉瓜", "Belize": "伯利兹",
    "Cuba": "古巴", "Jamaica": "牙买加", "Haiti": "海地",
    "Trinidad and Tobago": "特立尼达和多巴哥",
    "Dominican Republic": "多米尼加共和国",
    "Puerto Rico": "波多黎各", "Suriname": "苏里南",
    "Guyana": "圭亚那", "French Guiana": "法属圭亚那",
    "Martinique": "马提尼克", "Guadeloupe": "瓜德罗普",
    "Barbados": "巴巴多斯", "Bahamas": "巴哈马",
    "Bermuda": "百慕大", "Cayman Islands": "开曼群岛",
    "Turks and Caicos Islands": "特克斯和凯科斯群岛",
    "British Virgin Islands": "英属维尔京群岛",
    "US Virgin Islands": "美属维尔京群岛",
    "Anguilla": "安圭拉", "Montserrat": "蒙特塞拉特",
    "Antigua and Barbuda": "安提瓜和巴布达",
    "Saint Kitts and Nevis": "圣基茨和尼维斯",
    "Saint Lucia": "圣卢西亚",
    "Saint Vincent and the Grenadines": "圣文森特和格林纳丁斯",
    "Grenada": "格林纳达", "Dominica": "多米尼克",
    "Aruba": "阿鲁巴", "Curaçao": "库拉索",
    "Bonaire": "博奈尔", "Sint Maarten": "圣马丁",
    "Saint Martin": "法属圣马丁",
    "São Tomé and Príncipe": "圣多美和普林西比",
    "Sri Lanka": "斯里兰卡", "Seychelles": "塞舌尔",
    "Russia": "俄罗斯",
    "Rapid Wien": "维也纳快速", "SK Rapid Wien": "维也纳快速",
    "SK Sturm Graz": "格拉茨风暴", "Red Bull Salzburg": "萨尔茨堡红牛",
    "LASK": "林茨", "FK Austria Wien": "奥地利维也纳",
    "Wolfsberger AC": "沃尔夫斯贝格", "SV Ried": "里德",
    "WSG Tirol": "蒂罗尔", "TSV Hartberg": "哈特贝格",
    "SCR Altach": "阿尔塔赫", "SC Austria Lustenau": "奥地利卢斯特瑙",
    "Grazer AK 1902": "格拉茨AK",
    "GNK Dinamo Zagreb": "萨格勒布迪纳摩",
    "HNK Rijeka": "里耶卡", "HNK Hajduk Split": "哈伊杜克",
    "NK Aluminij Kidričevo": "阿卢米尼", "NK Bravo": "布拉沃",
    "NK Varaždin": "瓦拉日丁", "NK Celje": "采列",
    "FC København": "哥本哈根", "FC Midtjylland": "中日德兰",
    "Brøndby IF": "布隆德比", "AGF": "奥胡斯",
    "FC Nordsjælland": "北西兰", "Randers FC": "兰讷斯",
    "Silkeborg IF": "锡尔克堡", "Viborg FF": "维堡",
    "Odense Boldklub": "欧登塞", "Sønderjyske Fodbold": "森讷日斯克",
    "Lyngby": "林比", "AC Horsens": "霍森斯",
    "Bodø/Glimt": "博多闪耀", "Molde FK": "莫尔德",
    "Rosenborg BK": "罗森博格", "Viking FK": "维京",
    "SK Brann": "布兰", "Vålerenga IF": "瓦勒伦加",
    "Fredrikstad FK": "腓特烈斯塔", "Lillestrøm SK": "利勒斯特罗姆",
    "Tromsø IL": "特罗姆瑟", "Sarpsborg 08": "萨尔普斯堡",
    "Sandefjord Fotball": "桑德菲尤尔", "HamKam": "哈姆卡姆",
    "Kristiansund BK": "克里斯蒂安松", "Aalesunds FK": "奥勒松",
    "IK Start": "斯塔特", "KFUM Oslo": "KFUM奥斯陆",
    "Malmö FF": "马尔默", "AIK": "AIK", "Djurgårdens IF": "尤尔加登",
    "IFK Göteborg": "哥德堡", "BK Häcken": "赫根",
    "IF Elfsborg": "埃尔夫斯堡", "Hammarby IF": "哈马比",
    "Mjällby AIF": "米亚尔比", "GAIS": "盖斯",
    "Kalmar FF": "卡尔马", "Halmstads BK": "哈尔姆斯塔德",
    "IF Brommapojkarna": "布洛马波卡纳", "Västerås SK": "韦斯特罗斯",
    "Degerfors IF": "代格福什", "Örgryte IS": "厄格里特",
    "IK Sirius": "天狼星", "IFK Mariehamn": "玛丽港",
    "HJK": "HJK赫尔辛基", "Kuopion Palloseura": "库奥皮奥",
    "Inter Turku": "国际图尔库", "FC Lahti": "拉赫蒂",
    "Ilves": "伊尔韦斯", "SJK": "SJK", "VPS": "瓦萨",
    "AC Oulu": "奥卢", "IF Gnistan": "格尼斯坦",
    "FF Jaro": "雅罗", "Turun Palloseura": "TPS图尔库",
    "Lech Poznań": "波兹南莱赫", "Legia Warszawa": "华沙莱吉亚",
    "Raków Częstochowa": "拉科夫琴斯托霍瓦",
    "Wisła Kraków": "克拉科夫维斯瓦", "Wisła Płock": "普沃茨克维斯瓦",
    "Górnik Zabrze": "扎布热矿工", "GKS Katowice": "卡托维兹",
    "Jagiellonia Białystok": "比亚韦斯托克",
    "Motor Lublin": "卢布林", "Piast Gliwice": "格利维采",
    "Widzew Łódź": "罗兹维泽夫", "Radomiak Radom": "拉多姆",
    "KS Cracovia": "克拉科夫", "Pogoń Szczecin": "什切青",
    "Zagłębie Lubin": "卢宾", "MKS Korona Kielce": "凯尔采科罗纳",
    "Śląsk Wrocław": "弗罗茨瓦夫", "Wieczysta Kraków": "克拉科夫永恒",
    "Arka Gdynia": "格丁尼亚", "Wisła II Płock": "普沃茨克维斯瓦二队",
    "Chrobry Głogów": "格沃古夫", "Miedź Legnica": "莱格尼察",
    "Podbeskidzie Bielsko-Biała": "别尔斯科-比亚瓦",
    "Hutnik Kraków": "克拉科夫胡特尼克",
    "Znicz Pruszków": "普鲁什库夫", "ŁKS Łódź II": "罗兹ŁKS二队",
    "Podhale Nowy Targ": "新塔尔格",
    "MKS Chojniczanka Chojnice": "霍伊尼采",
    "Olimpia Grudziądz": "格鲁琼兹奥林匹亚",
    "Świt Skolwin Szczecin": "什切青希维特",
    "Warta Poznań": "波兹南瓦尔塔", "Resovia Rzeszów": "热舒夫",
    "Górnik Łęczna": "伦奇纳矿工", "KKS 1925 Kalisz": "卡利什",
    "Sandecja Nowy Sącz": "新松奇", "Rekord Bielsko-Biała": "别尔斯科-比亚瓦纪录",
    "GKS Tychy": "蒂黑", "Zagłębie Sosnowiec": "索斯诺维茨",
    "Unia Skierniewice": "斯凯尔涅维采联盟",
    "Sokół Kleczew": "克莱切夫猎鹰",
    "Stal Rzeszów": "热舒夫钢铁", "Puszcza Niepołomice": "涅波沃米采",
    "Bruk-Bet Termalica Nieciecza": "涅切查",
    "Wigry Suwałki": "苏瓦乌基", "Ruch Chorzów": "霍茹夫",
    "Polonia Bytom": "比托姆波兰", "Górnik Polkowice": "波尔科维采矿工",
    "Polonia Warszawa": "华沙波兰", "Legia II Warszawa": "华沙莱吉亚二队",
    "Siarka Tarnobrzeg": "塔尔诺布热格",
    "BKS Chemik Bydgoszcz": "比得哥什化学",
    "Kluczevia Stargard": "斯塔加德", "Pogoń Siedlce": "谢德尔采",
    "OKS Odra Opole": "奥波莱奥德拉",
    "MKS Kluczbork": "克卢奇堡", "KS Lechia Gdańsk": "格但斯克莱赫",
    "Polonia Środa Wielkopolska": "大波兰希罗达",
    "Widzew II Łódź": "罗兹维泽夫二队",
    "Śląsk II Wrocław": "弗罗茨瓦夫二队",
    "KS Beskid Andrychów": "安德雷胡夫",
    "Górnik Zabrze II": "扎布热矿工二队",
    "Stal Mielec": "梅莱茨钢铁",
    "MKS Avia Świdnik": "希维德尼克",
    "Lechia Zielona Góra": "绿山城莱赫",
    "Pogoń Grodzisk Mazowiecki": "马佐夫舍格罗济斯克",
    "DAC 1904": "多瑙斯特雷达", "FK Velež Mostar": "韦莱日莫斯塔尔",
    "Valletta FC": "瓦莱塔", "AEK Larnaca": "AEK拉纳卡",
    "Beitar Jerusalem": "贝塔尔耶路撒冷", "RFS": "RFS里加",
    "IF Vestri": "韦斯特里", "Dynamo Kyiv": "基辅迪纳摩",
    "PAOK": "PAOK塞萨洛尼基", "BATE Borisov": "鲍里索夫",
    "FC Sion": "锡永", "FC Santa Coloma": "圣科洛马",
    "ML Vitebsk": "维捷布斯克", "FK Sutjeska Nikšić": "苏捷斯卡",
    "FC Zimbru Chişinău": "津布鲁基希讷乌", "FC Noah": "诺亚",
    "FC Hradec Králové": "赫拉德茨克拉洛韦",
    "FC Universitatea Cluj": "克卢日大学",
    "Sheriff Tiraspol": "蒂拉斯波尔警长", "Maccabi Tel Aviv": "特拉维夫马卡比",
    "Dinamo Tbilisi": "第比利斯迪纳摩", "FK Žalgiris": "扎尔吉里斯",
    "FC Vaduz": "瓦杜兹", "Atlètic Club Escaldes": "埃斯卡尔德斯",
    "FCSB": "FCSB", "FK Auda": "奥达", "FC St. Gallen 1879": "圣加仑",
    "Ferencváros TC": "费伦茨瓦罗斯", "FK Vojvodina": "伏伊伏丁那",
    "Paksi FC": "保克什", "Panathinaikos FC": "帕纳辛奈科斯",
    "Polissya Zhytomyr": "日托米尔波利西亚", "Dinamo City": "地拉那迪纳摩",
    "FK Jablonec": "亚布洛内茨", "FC Lugano": "卢加诺",
    "Dukagjini": "杜卡吉尼", "LNZ Cherkasy": "切尔卡瑟LNZ",
    "FK Borac Banja Luka": "巴尼亚卢卡战士", "FC Petrocub Hîncesti": "彼得罗古",
    "MŠK Žilina": "日利纳", "Hapoel Tel Aviv": "特拉维夫夏普尔",
    "Ludogorets": "卢多戈雷茨", "NSÍ Runavík": "鲁纳维克",
    "FC Koper": "科佩尔", "KF Shkëndija": "什肯迪亚",
    "Derry City": "德里城", "HB Tórshavn": "托尔斯港HB",
    "Shelbourne": "谢尔本", "Nõmme Kalju": "诺梅卡柳",
    "Pafos FC": "帕福斯", "FK Partizan": "贝尔格莱德游击",
    "Una Strassen": "斯特拉森", "Stjarnan Garðabær": "加尔扎拜尔",
    "Valur Reykjavík": "雷克雅未克瓦鲁尔", "HŠK Zrinjski Mostar": "莫斯塔尔兹林斯基",
    "Bolívar": "玻利瓦尔", "Independiente Santa Fe": "圣菲独立",
    "Caracas F.C.": "加拉加斯卡拉卡斯", "O'Higgins": "奥希金斯",
    "UTA Arad": "阿拉德UTA", "SC Oțelul Galați": "加拉茨钢铁",
    "Arda Kardzhali": "阿尔达克尔贾利", "Slavia Sofia": "索菲亚斯拉维亚",
    "FC Argeș Pitești": "皮特什蒂阿尔杰什", "FC Petrolul Ploiești": "普洛耶什蒂石油",
    "Llaneros FC": "利亚内罗斯", "Deportivo Pereira": "佩雷拉体育",
    "Houston Dash": "休斯顿达什", "Bay FC": "湾区FC",
    "Orlando Pride": "奥兰多荣耀", "Chicago Stars FC": "芝加哥之星",
    "Birmingham Legion FC": "伯明翰军团", "New Mexico United": "新墨西哥联",
    "Deportivo Cali": "卡利体育", "Jaguares de Córdoba": "科尔多瓦美洲豹",
    "Portland Thorns FC": "波特兰荆棘", "NJ/NY Gotham FC": "新泽西/纽约哥谭",
    "Gold Coast Knights": "黄金海岸骑士", "Gold Coast United": "黄金海岸联",
    "Sporting Lagos FC": "拉各斯体育", "Rivers United": "河流联",
    "Ranchers Bees": "牧场蜜蜂", "Kano Pillars": "卡诺支柱",
    "Katsina United": "卡齐纳联", "Plateau United": "高原联",
    "Kwara United": "夸拉联", "Nasarawa United": "纳萨拉瓦联",
    "Niger Tornadoes": "尼日尔龙卷风", "Enyimba": "恩因巴",
    "Doma United FC": "多马联", "Bendel Insurance FC": "本代尔保险",
    "Barau FC": "巴劳FC", "Abia Warriors": "阿比亚战士",
    "Ikorodu City": "伊科罗杜城", "Inter Lagos FC": "拉各斯国际",
    "Shooting Stars": "流星", "Warri Wolves FC": "瓦里狼",
    "Kun Khalifat FC": "昆哈利法特", "Enugu Rangers International": "埃努古流浪者",
    "AS Port": "AS港", "Zamalek SC": "扎马雷克",
    "Vipers SC": "毒蛇SC", "FC Nouadhibou": "努瓦迪布",
    "Mighty Mukuru Wanderers": " mighty穆库鲁流浪者",
    "Simba SC": "辛巴SC", "APR FC": "APR FC",
    "FC Les Aigles du congo": "刚果老鹰", "Gor Mahia FC": "戈尔马希亚",
    "Pyramids FC": "金字塔FC", "Medeama SC": "梅德阿马",
    "Tout Puissant Mazembe": "马泽姆贝", "Al-Hilal Omdurman": "恩图曼新月",
    "Aigle Noir CS": "黑鹰", "Djoliba AC": "乔利巴",
    "Club Africain": "非洲人俱乐部", "ES Zarzis": "扎尔齐斯",
    "CS Sfaxien": "斯法克西恩", "ES Métlaoui": "梅特拉维",
    "Stade Tunisien": "突尼斯体育场", "CA Bizertin": "比塞大",
    "US Monastir": "莫纳斯提尔", "Etoile Sportive Du Sahel": "萨赫勒之星",
    "Espérance Sportive De Tunis": "突尼斯希望",
    "Avenir Sportif De La Marsa": "拉马尔萨",
    "US Ben Guerdane": "本盖尔丹", "CS Hammam-Lif": "哈马姆利夫",
    "ES Hammam-Sousse": "哈马姆苏斯", "JS Omrane": "奥姆兰",
    "Olympique Béja": "贝雅奥林匹克", "PS Sakiet Eddaïer": "萨基特西迪优素福",
    "Brooklyn FC": "布鲁克林FC", "Detroit City FC": "底特律城", "Miami FC": "迈阿密FC",
    "SC Jacksonville": "杰克逊维尔SC", "Rhode Island FC": "罗德岛FC", "Indy Eleven": "印地十一",
    "FC Tulsa": "塔尔萨FC", "Las Vegas Lights": "拉斯维加斯之光", "Sacramento Republic FC": "萨克拉门托共和",
    "Pittsburgh Riverhounds": "匹兹堡猎犬河", "San Antonio FC": "圣安东尼奥FC",
    "Louisville City FC": "路易斯维尔城", "Orange County SC": "橙县SC", "El Paso Locomotive FC": "埃尔帕索机车",
    "Colorado Springs Switchbacks FC": "科罗拉多斯普林斯", "Memphis 901 FC": "孟菲斯901",
    "Oakland Roots SC": "奥克兰根", "Tampa Bay Rowdies": "坦帕湾暴徒", "Phoenix Rising FC": "菲尼克斯崛起",
    "Charleston Battery": "查尔斯顿电池", "Hartford Athletic": "哈特福德竞技",
    "Atlético Nacional": "国民竞技", "Junior Barranquilla": "巴兰基亚青年",
}

# ==== 2026-10-01 队名批量补全 ====
TEAM_CN.update({
    'Deportes Tolima': '托利马体育',
    'Millonarios': '百万富翁',
    'Internacional de Bogotá': '波哥大国际',
    'Once Caldas': '卡尔达斯十一人',
    'Deportivo Pasto': '帕斯托体育',
    'América de Cali': '卡利美洲',
    'Independiente Medellín': '麦德林独立',
    'Alianza Valledupar FC': '巴耶杜帕尔联盟',
    'Cúcuta Deportivo': '库库塔体育',
    'Boyacá Chicó FC': '博亚卡奇科',
    'Rionegro Águilas Doradas': '里奥内格罗金鹰',
    'Atlético Bucaramanga': '布卡拉曼加竞技',
    'Deportes Quindío': '金迪奥体育',
    'Unión Magdalena': '马格达莱纳联盟',
    'Bogotá FC': '波哥大',
    'Tigres FC': '老虎',
    'Barranquilla FC': '巴兰基亚',
    'Real Cartagena': '皇家卡塔赫纳',
    'Envigado FC': '恩维加多',
    'Real Cundinamarca': '皇家昆迪纳马卡',
    'CSKA Sofia': '索菲亚中央陆军',
    'Levski Sofia': '索菲亚列夫斯基',
    'FC CSKA 1948 Sofia': '索菲亚中央陆军1948',
    'Lokomotiv Sofia': '索菲亚火车头',
    'Cherno More Varna': '瓦尔纳黑海',
    'Lokomotiv Plovdiv': '普罗夫迪夫火车头',
    'FK Dunav Ruse': '鲁塞多瑙河',
    'Botev Plovdiv': '普罗夫迪夫博特夫',
    'FK Spartak Varna': '瓦尔纳斯巴达克',
    'FK Septemvri Sofia': '索菲亚九月',
    'Botev Vratsa': '弗拉察博特夫',
    'Universitatea Craiova': '克拉约瓦大学',
    'FCSB': '布加勒斯特星',
    'CFR 1907 Cluj': '克卢日',
    'FCV Farul Constanța': '康斯坦察灯塔',
    'FC Dinamo București': '布加勒斯特迪纳摩',
    'FC Botoșani': '博托沙尼',
    'FC Voluntari': '沃尔伦塔里',
    'Sepsi OSK Sfântu Gheorghe': '圣格奥尔基塞普西',
    'FC Rapid București': '布加勒斯特快速',
    'FC Corvinul Hunedoara': '胡内多阿拉科维努尔',
    'FK Csíkszereda Miercurea Ciuc': '米耶尔库雷亚丘克',
    'FC Thun': '图恩',
    'Servette FC': '塞尔维特',
    'FC Lausanne-Sport': '洛桑体育',
    'FC Luzern': '卢塞恩',
    'BSC Young Boys': '伯尔尼年轻人',
    'FC Zürich': '苏黎世',
    'Basel': '巴塞尔',
    'Grasshopper Club Zürich': '苏黎世草蜢',
    'Fenerbahçe': '费内巴切',
    'North Carolina Courage': '北卡罗来纳勇气',
    'Angel City FC': '天使城',
    'Racing Louisville': '路易斯维尔竞技',
    'Denver Summit FC': '丹佛峰',
    'Seattle Reign FC': '西雅图君临',
    'Washington Spirit': '华盛顿精神',
    'Kansas City Current': '堪萨斯城潮流',
    'Utah Royals FC': '犹他皇家',
    'San Diego Wave FC': '圣迭戈波浪',
    'Boston Legacy FC': '波士顿遗产',
    'Lexington SC': '莱克星顿SC',
    'Monterey Bay FC': '蒙特雷湾',
    'Loudoun United FC': '劳登联',
    'FC Tampa Bay Rowdies': '坦帕湾暴徒',
    'CRB': 'CRB',
    'Grêmio Novorizontino': '新奥里藏蒂诺',
    'Middlesbrough': '米德尔斯堡',
    'Norwich City': '诺维奇',
    'Leyton Orient': '莱顿东方',
    'Fleetwood Town': '弗利特伍德',
    'Reading': '雷丁',
    'Sheffield United': '谢菲尔德联',
    'Millwall': '米尔沃尔',
    'Peterborough United': '彼得堡联',
    'Southampton': '南安普顿',
    'York City': '约克城',
    'Wycombe Wanderers': '韦康比流浪者',
    'Grimsby Town': '格林斯比',
    'Crewe Alexandra': '克鲁',
    'Watford': '沃特福德',
    'Stoke City': '斯托克城',
    'Barnsley': '巴恩斯利',
    'Cardiff City': '卡迪夫城',
    'Preston North End': '普雷斯顿',
    'AFC Wimbledon': 'AFC温布尔登',
    'Plymouth Argyle': '普利茅斯',
    'Chesterfield': '切斯特菲尔德',
    'Crawley Town': '克劳利',
    'Charlton Athletic': '查尔顿',
    'Woking': '沃金',
    'Harrogate Town': '哈罗盖特',
    'Walsall': '沃尔索尔',
    'Birmingham City': '伯明翰',
    'Lincoln City': '林肯城',
    'Boston United': '波士顿联',
    'Shrewsbury Town': '什鲁斯伯里',
    'Stevenage': '斯蒂夫尼奇',
    'Rochdale': '罗奇代尔',
    'Wrexham': '雷克瑟姆',
    'West Bromwich Albion': '西布罗姆维奇',
    'Bristol City': '布里斯托尔城',
    'Cambridge United': '剑桥联',
    'Queens Park Rangers': '女王公园巡游者',
    'Sheffield Wednesday': '谢菲尔德星期三',
    'Burton Albion': '伯顿',
    'Stockport County': '斯托克波特',
    'Gillingham': '吉林汉姆',
    'Leicester City': '莱斯特城',
    'Derby County': '德比郡',
    'Bradford City': '布拉德福德',
    'Bristol Rovers': '布里斯托尔流浪者',
    'Colchester United': '科尔切斯特联',
    'Rotherham United': '罗瑟汉姆',
    'Cheltenham Town': '切尔滕纳姆',
    'Bolton Wanderers': '博尔顿',
    'Oldham Athletic': '奥尔德姆',
    'Newport County': '纽波特郡',
    'Notts County': '诺茨郡',
    'Accrington Stanley': '阿克宁顿',
    'Blackpool': '布莱克浦',
    'Doncaster Rovers': '唐卡斯特',
    'Solihull Moors': '索利赫尔摩尔',
    'Yeovil Town': '耶奥维尔',
    'FC Halifax Town': '哈利法克斯',
    'Forest Green Rovers': '森林绿流浪者',
    'Kidderminster Harriers': '基德明斯特',
    'Wigan Athletic': '维冈竞技',
    'Exeter City': '埃克塞特城',
    'Blackburn Rovers': '布莱克本',
    'Boreham Wood': '博勒姆伍德',
    'Scunthorpe United': '斯肯索普联',
    'AFC Fylde': 'AFC法尔德',
    'Hartlepool United': '哈特尔浦联',
    'Swansea City': '斯旺西城',
    'Bromley': '布罗姆利',
    'Salford City': '索尔福德城',
    'Mansfield Town': '曼斯菲尔德',
    'Northampton Town': '北安普顿',
    'Barnet': '巴尼特',
    'Huddersfield Town': '哈德斯菲尔德',
    'Sutton United': '萨顿联',
    'Luton Town': '卢顿',
    'Eastleigh': '伊斯特利',
    'Milton Keynes Dons': '米尔顿凯恩斯',
    'Port Vale': '维尔港',
    'Swindon Town': '斯温登',
    'Gateshead': '盖茨黑德',
    'Altrincham FC': '奥尔特林厄姆',
    'Aldershot Town': '奥尔德肖特',
    'Wealdstone': '韦尔德斯通',
    'Tamworth': '塔姆沃思',
    'Barrow AFC': '巴罗',
    'Carlisle United': '卡莱尔联',
    'Southend United': '绍森德联',
    'Hornchurch': '霍恩彻奇',
    'Worthing FC': '沃辛',
    'Oxford United': '牛津联',
    'Tranmere Rovers': '特兰米尔',
    'Portsmouth': '朴茨茅斯',
    'Tottenham Hotspur': '托特纳姆热刺',
    'Brighton & Hove Albion': '布莱顿',
    'Bury FC': '伯里',
    'Worcester City': '伍斯特城',
    'Boldmere St Michaels FC': '博尔德米尔圣迈克尔',
    'Warrington Rylands 1906 FC': '沃灵顿莱兰兹',
    'Hemel Hempstead': '赫默尔亨普斯特德',
    'Emley AFC': '埃姆利',
    'Wingate & Finchley': '温盖特与芬奇利',
    'Chippenham Town': '奇彭纳姆',
    'Witton Albion FC': '威顿阿尔比恩',
    'Ossett United': '奥塞特联',
    'Knowle FC': '诺尔',
    'Exmouth Town': '埃克斯茅斯',
    'Yate Town': '亚特',
    'Leamington': '利明顿',
    'South Shields': '南希尔兹',
    'Gorleston FC': '戈尔斯顿',
    'Barton Town': '巴顿',
    'Torquay United': '托基联',
    'Redditch United': '雷迪奇联',
    'FC United of Manchester': '曼彻斯特联FC',
    'Gainsborough Trinity': '盖恩斯伯勒三一',
    'Stratford Town': '斯特拉特福',
    'Bury Town FC': '伯里镇',
    'AFC Stoneham': '斯托纳姆',
    'Workington': '沃金顿',
    'Spennymoor Town': '斯彭尼穆尔',
    'Evesham United': '伊夫舍姆联',
    'Chorley FC': '乔利',
    'Three Bridges FC': '三桥',
    'Quorn FC': '科恩',
    'Flackwell Heath': '弗拉克韦尔希思',
    'Aveley FC': '阿夫利',
    'Curzon Ashton FC': '柯曾阿什顿',
    'Bath City': '巴斯城',
    'Cleethorpes Town': '克利索普斯',
    'Avro FC': '阿夫罗',
    'Garforth Town AFC': '加福斯',
    'Cambridge City': '剑桥城',
    'Faversham Town': '法弗舍姆',
    'Dulwich Hamlet': '德威哈姆雷特',
    'Bamber Bridge FC': '班伯布里奇',
    'Alfreton Town FC': '阿尔弗雷顿',
    'Buckhurst Hill': '巴克赫斯特山',
    'Fakenham Town': '法肯纳姆',
    'Hitchin Town': '希钦',
    'Needham Market FC': '尼德姆市场',
    'Havant & Waterlooville': '哈文特与沃特卢维尔',
    'Kettering Town': '凯特林',
    'Brentwood Town': '布伦特伍德',
    'AFC Whyteleafe': '怀特利夫',
    'Bishop Auckland': '奥克兰主教',
    'Redcar Athletic': '雷德卡竞技',
    'Weston Super Mare': '滨海韦斯顿',
    'Thame United': '泰姆联',
    'Walton & Hersham FC': '沃尔顿与赫舍姆',
    'Maidenhead United': '梅登黑德联',
    'Buxton FC': '巴克斯顿',
    'Bedford Town': '贝德福德',
    'Brackley Town': '布拉克利',
    'Dagenham & Redbridge': '达根汉姆与雷德布里奇',
    'Worksop Town FC': '沃克索普',
    'Farnborough': '法恩伯勒',
    'Truro City': '特鲁罗城',
    'Kingstonian': '金斯顿尼安',
    'Pontefract Collieries FC': '庞蒂弗拉克特煤矿',
    'Shepshed Dynamo': '谢普谢德迪纳摩',
    'Hanwell Town': '汉威尔',
    'Cheshunt FC': '切森特',
    'Bradford Park Avenue AFC': '布拉德福德公园大道',
    'Weymouth FC': '韦茅斯',
    'Hyde United FC': '海德联',
    'Wythenshawe FC': '威森肖',
    'Newcastle Town FC': '纽卡斯尔镇',
    'Maldon & Tiptree FC': '莫尔登与蒂普特里',
    'Welling United FC': '威灵联',
    'East Grinstead Town': '东格林斯特德',
    'Trafford FC': '特拉福德',
    'Yaxley FC': '亚克斯利',
    'Ware FC': '韦尔',
    'Biggleswade Town': '比格尔斯韦德',
    'Stanway Rovers': '斯坦韦流浪者',
    'Wellingborough Town': '韦灵伯勒',
    'Concord Rangers': '康科德流浪者',
    'Bourne Town': '伯恩',
    'Crowborough Athletic': '克劳伯勒竞技',
    'Banbury United': '班伯里联',
    'Macclesfield FC': '麦克尔斯菲尔德',
    'Wimborne Town': '温伯恩',
    'Horsham FC': '霍舍姆',
    'Ebbsfleet United': '埃布斯弗利特联',
    'Ashton United FC': '阿什顿联',
    "King's Lynn Town": '金斯林',
    'AFC Portchester': '波特切斯特',
    'Waltham Abbey': '沃尔瑟姆修道院',
    'Telford United': '特尔福德联',
    'Uxbridge': '阿克斯布里奇',
    'Merthyr Town': '梅瑟蒂德菲尔',
    'Atlético Madrid': '马德里竞技',
    'Club Atlético de Madrid': '马德里竞技',
    'Real Sociedad B': '皇家社会B',
    'Real Oviedo': '皇家奥维耶多',
    'Eibar': '埃瓦尔',
    'SD Eibar': '埃瓦尔',
    'Burgos Club de Fútbol': '布尔戈斯',
    'UD Las Palmas': '拉斯帕尔马斯',
    'Sporting Gijón': '希洪竞技',
    'Córdoba': '科尔多瓦',
    'AD Ceuta': '休达',
    'Albacete Balompié': '阿尔瓦塞特',
    'CD Eldense': '埃尔登塞',
    'CD Tenerife': '特内里费',
    'Costa Adeje Tenerife': '特内里费',
    'Granada': '格拉纳达',
    'Granada Club de Fútbol': '格拉纳达',
    'Leganés': '莱加内斯',
    'Real Valladolid': '皇家巴利亚多利德',
    'FC Andorra': '安道尔',
    'CE Sabadell': '萨瓦德尔',
    'Madrid CFF': '马德里CFF',
    'Celta Fortuna': '塞尔塔福图纳',
    'RCD Espanyol de Barcelona': '西班牙人',
    'CD Castellón': '卡斯特利翁',
    'Real Club Deportivo de A Coruña': '拉科鲁尼亚',
    'Fútbol Club Barcelona': '巴塞罗那',
    'FC Badalona': '巴达洛纳',
    'Logroño United': '洛格罗尼奥联',
    "US Boulogne Côte-d'Opale": '布洛涅',
    'Pau FC': '波城',
    'Metz': '梅斯',
    'Sochaux': '索肖',
    'Clermont Foot': '克莱蒙',
    'USL Dunkerque': '敦刻尔克',
    'Rodez AF': '罗德兹',
    'Nantes': '南特',
    'Montpellier': '蒙彼利埃',
    'Stade de Reims': '兰斯',
    'Red Star FC': '红星',
    'Dijon': '第戎',
    'Stade Lavallois': '拉瓦勒',
    'Grenoble Foot 38': '格勒诺布尔',
    'Guingamp': '甘冈',
    'Annecy FC': '阿讷西',
    'Saint-Étienne': '圣埃蒂安',
    'Nancy': '南锡',
    'AS Monaco': '摩纳哥',
    'C.F. Os Belenenses': '贝伦人',
    'Amarante FC': '阿马兰特',
    'Varzim SC': '瓦尔津',
    'Penafiel': '佩纳菲耶尔',
    'Tondela': '通德拉',
    'CD Mafra': '马夫拉',
    'Feirense': '费伦斯',
    'AVS - Futebol SAD': 'AVS',
    'AD Fafe': '法菲',
    'Académica Coimbra': '科英布拉大学',
    'Atletico CP': '竞技CP',
    'União de Leiria': '莱里亚联盟',
    'Torreense': '托雷恩塞',
    'Portimonense SAD': '波尔蒂芒人',
    'Leixões SC': '莱雄伊什',
    'GD Vitória Sernache': '塞纳谢维多利亚',
    'Felgueiras': '费尔盖拉斯',
    'Chaves': '沙维什',
    'Lusitano Ginásio Clube': '卢西塔诺',
    'SC Covilhã': '科维良',
    'AD Marco 09': '马尔科09',
    'Vizela': '维泽拉',
    'CD Trofense': '特罗芬塞',
    'Lusitânia Lourosa': '洛罗萨卢西塔尼亚',
    'Paços de Ferreira': '费雷拉',
    'SC Vianense': '维亚纳',
    'SC São João Ver': '圣若昂维尔',
    'Caldas SC': '卡尔达斯',
    'USC Paredes': '帕雷德斯',
    'SC Farense': '法鲁人',
    'UD Santarém': '圣塔伦',
    'Louletano DC': '洛莱塔诺',
    'UD Oliveirense': '奥利维伦斯',
    'Leça FC': '莱萨',
    'CD Fátima': '法蒂玛',
    'Estrela Calheta FC': '卡列塔星',
    'AD Fazendense': '法曾登塞',
    'SC Beira-Mar': '贝拉马尔',
    'SU Sintrense': '辛特伦塞',
    'Real SC': '皇家SC',
    'O Elvas CAD': '埃尔瓦斯',
    'CD Cinfães': '辛方伊什',
    'AD Ponte da Barca': '蓬蒂达巴尔卡',
    'FC Serpa': '塞尔帕',
    'Mortágua': '莫尔塔瓜',
    'FC Alverca B': '阿尔韦卡B',
    'SC Mineiro Aljustrelense': '阿尔茹斯特雷尔矿工',
    'FC Vinhais': '维尼艾什',
    'At. Malveira': '马尔韦拉竞技',
    'AD Sanjoanense': '圣若昂人',
    '1º Dezembro': '12月1日',
    'Gd Nazarenos': '纳扎雷诺斯',
    'Guarda FC': '瓜尔达',
    'Associação Naval 1893': '海军1893',
    'Sport Comércio e Salgueiros': '萨尔盖罗斯',
    'FC Tirsense': '蒂尔森塞',
    'GD Alcochetense': '阿尔科谢滕塞',
    'Sertanense': '塞尔坦嫩塞',
    'União Desportiva da Serra': '塞拉联盟',
    'Grupo Desportivo de Bragança': '布拉干萨',
    'GD Lagoa': '拉戈阿',
    'SC Maria da Fonte': '玛丽亚达丰特',
    'Imortal Deportivo Clube': '不死体育',
    'AD Castro Daire': '卡斯特罗代雷',
    'AD Ovarense': '奥瓦伦塞',
    'Amora FC': '阿莫拉',
    'Oliveira Hospital': '奥利维拉医院',
    'AD Os Limianos': '利米亚诺斯',
    'AD Camacha': '卡马查',
    'FC Maia Lidador': '马亚利达多尔',
    'CF Marialvas': '马里亚尔瓦斯',
    'CD Celoricense': '塞洛里库',
    'CO Montijo': '蒙蒂茹',
    'UD Sousense': '索森塞',
    'Benfica Castelo Branco': '本菲卡布朗库堡',
    'AC Vila Meã': '维拉梅昂',
    'CDC Montalegre': '蒙塔莱格里',
    'Vitória de Setúbal': '塞图巴尔维多利亚',
    'GD Portel': '波特尔',
    'Chaves B': '沙维什B',
    'AD Machico': '马希库',
    'CF União de Lamas': '拉马斯联盟',
    'Brito SC': '布里托',
    'AD Nogueirense': '诺盖伦塞',
    'SC Braga B': '布拉加B',
    'Santa Clara Azores B': '圣克拉拉B',
    'SC Penalva do Castelo': '佩纳尔瓦杜卡斯特洛',
    'CD Paços de Brandão': '帕苏斯德布兰当',
    'Rebordosa AC': '雷博尔多萨',
    'JD Lajense': '拉延塞',
    'Vitória SC B': '吉马良斯B',
    'Arezzo': '阿雷佐',
    'Benevento': '贝内文托',
    'Mantova': '曼托瓦',
    'Union Brescia': '布雷西亚联',
    'Ravenna': '拉文纳',
    'US Avellino 1912': '阿韦利诺',
    'Padova': '帕多瓦',
    'Modena': '摩德纳',
    'Carrarese': '卡拉雷塞',
    'Juve Stabia': '斯塔比亚尤文',
    'Virtus Entella': '恩特拉',
    'Cesena': '切塞纳',
    'OFI Crete': '克里特OFI',
    'AEK Athens': '雅典AEK',
    'Olympiacos FC': '奥林匹亚科斯',
    'PS Kalamata': '卡拉马塔',
    'GFS Panetolikos': '帕内托利科斯',
    'NPS Volos': '沃洛斯',
    'Aris Thessaloniki': '塞萨洛尼基阿里斯',
    'APS Atromitos Athinon': '雅典阿特罗米托斯',
    'AE Kifisia': '基菲夏',
    'Asteras Aktor': '阿斯特拉斯',
    'POT Iraklis': '伊拉克利斯',
    'APO Levadiakos': '莱瓦迪亚科斯',
    'Bayer 04 Leverkusen': '勒沃库森',
    'Bahlinger SC': '巴林格',
    'Westfalia Rhynern': '威斯特法利亚里嫩',
    'FC Carl Zeiss Jena': '卡尔蔡司耶拿',
    'Rot-Weiss Essen': '红白埃森',
    'Fortuna Düsseldorf': '杜塞尔多夫',
    '1.FC Phönix Lübeck': '吕贝克凤凰',
    'SC Verl': '费尔',
    'VSG Altglienicke': '阿尔特格利尼克',
    'Hallescher FC': '哈雷',
    'Hamburg-Eimsbütteler Ballspiel Club 1911': '汉堡艾姆斯比特尔',
    'SK Slavia Praha': '布拉格斯拉维亚',
    'FC Viktoria Plzeň': '比尔森胜利',
    'AC Sparta Praha': '布拉格斯巴达',
    'Patro Eisden Maasmechelen': '马斯梅赫伦',
    'Jong KRC Genk U23': '亨克青年队',
    'KAS Eupen': '欧本',
    'KSC Lokeren': '洛克伦',
    'RFC Seraing': '塞兰',
    'Royal Excelsior Virton': '维尔通',
    'KVZ FC': 'KVZ',
    'Club NXT U23': '布鲁日NXT',
    'Royal Francs Borains': '弗朗斯博兰',
    'FCV Dender': '登德尔',
    'KAA Gent Reserve U23': '根特预备队',
    'RSCA Futures U23': '安德莱赫特未来',
    'RFC Liège': '列日',
    'Sporting CP B U21': '葡萄牙体育B U21',
    'Riga FC': '里加',
    'FC Drita': '德里塔',
    'FC Kairat Almaty': '阿拉木图凯拉特',
    'FK Kauno Žalgiris': '考纳斯萨尔基里斯',
    'FK Crvena zvezda': '贝尔格莱德红星',
    'Pyunik Yerevan': '埃里温凤凰',
    'Zirə FK': '齐拉',
    'FCI Levadia Tallinn': '塔林利瓦迪亚',
    'KF Ballkani': '巴尔卡尼',
    "Hapoel Be'er Sheva": '贝尔谢巴夏普尔',
    'ŠK Slovan Bratislava': '布拉迪斯拉发斯拉夫人',
    'FC Ararat-Armenia': '亚美尼亚阿拉拉特',
    'Sabah FK': '萨巴赫',
    'Omonia Nicosia': '尼科西亚奥莫尼亚',
    'Lincoln Red Imps': '林肯红魔',
    'Shamrock Rovers': '沙姆洛克流浪者',
    'Qarabağ FK': '卡拉巴赫',
    'Víkingur Reykjavík': '雷克雅未克维京人',
    'Klaksvíkar Ítróttarfelag': '克拉克斯维克',
    'KF Egnatia': '埃格纳蒂亚',
    "Inter Club d'Escaldes": '埃斯卡尔德斯国际',
    'FC Dila Gori': '哥里迪拉',
    'FK Vardar Skopje': '斯科普里瓦尔达尔',
    'FC Spartak Trnava': '特尔纳瓦斯巴达克',
    'Floriana FC': '弗洛里亚纳',
    'FK Panevėžys': '帕涅韦日斯',
    'Atert Bissen': '阿特尔特比森',
    'Neftçi PFK': '巴库石油工人',
    'FK Liepaja': '利耶帕亚',
    'FC Alashkert': '阿拉什科特',
    'FC Malisheva': '马利舍瓦',
    'FK Železničar Pančevo': '潘切沃铁路工人',
    'SP Tre Fiori': '特雷菲奥里',
    'FC Iberia 1999': '伊比利亚1999',
    'FC Tobyl': '托博尔',
    'Dinamo Minsk': '明斯克迪纳摩',
    'APR FC': 'APR',
    'FC Alpendorada': '阿尔彭多拉达',
    'AIK': 'AIK索尔纳',
    'SJK': 'SJK塞伊奈约基',
    'Paide Linnameeskond': '派德',
    'Flora Tallinn': '塔林弗洛拉',
    'Bohemian FC': '波希米亚人',
    'The New Saints': '新圣徒',
    'Larne FC': '拉恩',
    'Coleraine FC': '科尔雷恩',
    'MAS de Fès': '非斯MAS',
    'Union Sportive Amal Tiznit': '提兹尼特阿马尔',
    'Union Touarga Sport': '图瓦尔加体育',
    'Difaâ Hassani El-Jadidi': '杰迪代哈萨尼',
    'Wydad Casablanca': '卡萨布兰卡维达德',
    'Moghreb Atlético Tetuán': '得土安竞技',
    'Kawkab Athletic Club Marrakech': '马拉喀什体育',
    'Ittihad Tanger': '丹吉尔联合',
    'Fath Union Sport': '拉巴特FUS',
    'CODM Meknès': '梅克内斯',
    'Widad Temara': '特马拉维达德',
    'RS Berkane': '贝尔卡尼',
    'Renaissance Zemamra': '泽马姆拉复兴',
    "Hassania d'Agadir": '阿加迪尔哈萨尼亚',
    'MC Alger': '阿尔及尔MC',
    'JS Saoura': '萨乌拉',
    'Al-Merrikh Khartoum Club': '喀土穆梅里克',
    'Al-Hilal': '利雅得新月',
    'Al-Nassr': '利雅得胜利',
    'Abha': '艾卜哈',
    'Horoya': '霍罗亚',
    'ASEC Mimosas': '米莫萨斯',
    'Young Africans SC': '非洲年轻人',
    'Gaborone United': '哈博罗内联',
    'Power Dynamos': '电力迪纳摩',
    'Atlético Petróleos de Luanda': '罗安达石油竞技',
    'Rahimo FC': '拉希莫',
    'Stade Malien': '马里体育场',
    'Colombe FC': '科隆布',
    'ASN Nigelec': '尼日尔电力',
    'SOBEMAP FC': '索贝马普',
    'União Desportiva do Songo': '松戈联盟',
    'FC San Pedro': '圣佩德罗',
    'Swehly SC': '斯韦利',
    'ASC Kara': '卡拉',
    'Primeiro de Agosto': '八月一日',
    'Desportivo da Huíla': '威拉体育',
    'Wiliete SC': '维利埃特',
    '1º de Maio de Benguela': '本格拉五月一日',
    'FC Luanda': '罗安达',
    'Académica Petróleos do Lobito': '洛比托石油大学',
    'Recreativo do Libolo': '利博洛娱乐',
    'CD Lunda Sul': '南隆达',
    'Cienciano': '西恩西亚诺',
    'Montevideo City Torque': '蒙得维的亚城扭矩',
    'LDU': '基多大学',
    'Independiente del Valle': '山谷独立',
    'Recoleta FC': '雷科莱塔',
    'Universidad Católica': '天主教大学',
    'Cerro Porteño': '波特诺山丘',
    'Coquimbo Unido': '科金博联',
    'Macará': '马卡拉',
    'Olimpia': '奥林匹亚',
    'Nacional': '民族',
    'Universidad Central': '中央大学',
    'Club Sporting Cristal': '水晶体育',
    'Shakhtar Donetsk': '顿涅茨克矿工',
    'Peninsula Power': '半岛电力',
    'Lions FC': '狮子FC',
    'Moreton City Excelsior FC': '莫顿城',
    'Wynnum Wolves FC': '温纳姆狼',
    'Rochedale Rovers': '罗奇代尔流浪者',
    'Magic United TFA': '魔术联',
    'Brisbane Roar Youth': '布里斯班狮吼青年队',
    'Olympic FC': '奥林匹克FC',
    'Brisbane City': '布里斯班城',
    'Eastern Suburbs': '东郊',
    'Florgrade FC': '弗洛格拉德',
    'Korona II Kielce': '凯尔采科罗纳二队',
    'Wikęd Luzino': '卢齐诺',
    'KS Górnik Polkowice': '波尔科维采矿工',
    'OKS Sokół Ostróda': '奥斯特鲁达猎鹰',
    'ŁKS Łódź': '罗兹',
    'ETO FC Győr': '杰尔',
    'Debreceni VSC': '德布勒森',
})

TEAM_CN.update({"Apollon Limassol": "阿波罗利马索尔"})


TEAM_CN.update({
    "DR Congo": "刚果民主共和国",
    "Uganda": "乌干达",
    "Mauritius": "毛里求斯",
})

